// Mots secrets par catégorie (générés, sans doublons).
module.exports = {
  "Animaux": [
    "Girafe", "Éléphant", "Pieuvre", "Escargot", "Kangourou", "Pingouin", "Serpent", "Papillon",
    "Tortue", "Requin", "Hérisson", "Flamant rose", "Crocodile", "Chauve-souris", "Lapin", "Hibou",
    "Baleine", "Araignée", "Cheval", "Chameau", "Paon", "Crabe", "Singe", "Lion",
    "Tigre", "Zèbre", "Ours", "Ours polaire", "Panda", "Koala", "Loup", "Renard",
    "Écureuil", "Castor", "Raton laveur", "Blaireau", "Taupe", "Souris", "Rat", "Hamster",
    "Cochon d'Inde", "Chat", "Chien", "Vache", "Taureau", "Mouton", "Chèvre", "Cochon",
    "Poule", "Coq", "Poussin", "Canard", "Oie", "Dinde", "Âne", "Lama",
    "Alpaga", "Dromadaire", "Hippopotame", "Rhinocéros", "Gorille", "Chimpanzé", "Orang-outan", "Lémurien",
    "Paresseux", "Tatou", "Fourmilier", "Ornithorynque", "Wombat", "Suricate", "Hyène", "Guépard",
    "Léopard", "Panthère", "Jaguar", "Lynx", "Puma", "Bison", "Buffle", "Yack",
    "Élan", "Cerf", "Biche", "Chevreuil", "Sanglier", "Antilope", "Gazelle", "Gnou",
    "Okapi", "Morse", "Phoque", "Otarie", "Loutre", "Dauphin", "Orque", "Narval",
    "Cachalot", "Méduse", "Étoile de mer", "Hippocampe", "Homard", "Crevette", "Calamar", "Huître",
    "Moule", "Oursin", "Corail", "Poisson rouge", "Poisson-clown", "Poisson-globe", "Raie", "Espadon",
    "Saumon", "Thon", "Truite", "Sardine", "Anguille", "Piranha", "Carpe", "Brochet",
    "Grenouille", "Crapaud", "Salamandre", "Triton", "Lézard", "Caméléon", "Iguane", "Gecko",
    "Cobra", "Python", "Vipère", "Boa", "Alligator", "Varan", "Dragon de Komodo", "Aigle",
    "Faucon", "Vautour", "Condor", "Chouette", "Corbeau", "Pie", "Pigeon", "Colombe",
    "Moineau", "Merle", "Rouge-gorge", "Mésange", "Hirondelle", "Perroquet", "Perruche", "Toucan",
    "Colibri", "Pélican", "Mouette", "Albatros", "Cigogne", "Héron", "Grue", "Cygne",
    "Autruche", "Émeu", "Kiwi", "Dodo", "Pic-vert", "Martin-pêcheur", "Manchot", "Macareux",
    "Fourmi", "Abeille", "Guêpe", "Frelon", "Bourdon", "Coccinelle", "Libellule", "Sauterelle",
    "Criquet", "Grillon", "Cigale", "Mouche", "Moustique", "Puce", "Pou", "Cafard",
    "Scarabée", "Mante religieuse", "Chenille", "Ver de terre", "Limace", "Mille-pattes", "Scorpion", "Tique",
    "Luciole", "Phasme", "Termite", "Mite", "Chiot", "Chaton", "Poulain", "Veau",
    "Agneau", "Porcelet", "Caneton", "Têtard", "Lionceau", "Ourson", "Dinosaure", "Tyrannosaure",
    "Tricératops", "Diplodocus", "Ptérodactyle", "Mammouth", "Tigre à dents de sabre", "Stégosaure", "Vélociraptor", "Chinchilla",
    "Furet", "Hermine", "Belette", "Putois", "Mangouste", "Porc-épic", "Musaraigne", "Marmotte",
    "Chamois", "Bouquetin", "Mouflon", "Renne", "Caribou", "Orignal", "Tapir", "Capybara",
    "Babouin", "Mandrill", "Gibbon", "Ouistiti", "Dingo", "Coyote", "Chacal", "Fennec",
    "Bélier", "Bouc", "Jument", "Poney", "Mulet", "Zébu", "Lamantin", "Dugong",
    "Baudroie", "Poisson-scie", "Requin-marteau", "Barracuda", "Murène", "Mérou", "Bernard-l'ermite", "Axolotl",
    "Ara", "Cacatoès", "Faisan", "Perdrix", "Caille", "Pintade", "Ibis", "Marabout",
    "Kookaburra", "Casoar", "Nandou", "Harfang", "Épervier", "Buse", "Milan", "Goéland",
    "Cormoran", "Fou de Bassan", "Bécasse", "Huppe", "Geai", "Pinson", "Rossignol", "Canari",
    "Étourneau", "Corneille", "Panda roux", "Loup arctique", "Lièvre", "Cobaye", "Hyène tachetée", "Gerbille",
    "Phacochère", "Zorille", "Yak des montagnes", "Tortue de mer", "Poisson volant", "Requin baleine", "Pingouin empereur", "Mouette rieuse",
    "Vache laitière", "Chat sauvage", "Chien de traîneau", "Caniche", "Teckel", "Dalmatien", "Chihuahua", "Bouledogue",
    "Berger allemand", "Saint-Bernard", "Lévrier", "Raie manta", "Tortue géante", "Poisson-chat", "Silure", "Esturgeon",
    "Hareng", "Maquereau", "Morue", "Sole", "Daurade", "Seiche", "Langouste"
  ],
  "Nourriture": [
    "Pizza", "Banane", "Croissant", "Hamburger", "Glace", "Spaghetti", "Ananas", "Baguette",
    "Fromage", "Sushi", "Pastèque", "Cerise", "Œuf au plat", "Carotte", "Gâteau", "Hot-dog",
    "Brocoli", "Popcorn", "Donut", "Raisin", "Fraise", "Taco", "Crêpe", "Pomme",
    "Poire", "Orange", "Citron", "Citron vert", "Pamplemousse", "Mandarine", "Clémentine", "Mangue",
    "Papaye", "Noix de coco", "Grenade", "Figue", "Datte", "Abricot", "Pêche", "Nectarine",
    "Prune", "Mirabelle", "Framboise", "Myrtille", "Mûre", "Groseille", "Cassis", "Melon",
    "Litchi", "Fruit de la passion", "Tomate", "Concombre", "Courgette", "Aubergine", "Poivron", "Piment",
    "Oignon", "Ail", "Échalote", "Poireau", "Chou", "Chou-fleur", "Chou de Bruxelles", "Épinard",
    "Salade", "Laitue", "Radis", "Navet", "Betterave", "Céleri", "Asperge", "Artichaut",
    "Haricot vert", "Petit pois", "Maïs", "Pomme de terre", "Patate douce", "Potiron", "Citrouille", "Courge",
    "Fenouil", "Endive", "Gingembre", "Persil", "Basilic", "Menthe", "Lentilles", "Pois chiche",
    "Riz", "Pâtes", "Lasagnes", "Ravioli", "Gnocchi", "Couscous", "Paella", "Risotto",
    "Quiche", "Tarte aux pommes", "Tarte au citron", "Éclair au chocolat", "Macaron", "Madeleine", "Cookie", "Muffin",
    "Cupcake", "Brownie", "Gaufre", "Pancake", "Churros", "Beignet", "Chouquette", "Pain au chocolat",
    "Brioche", "Pain de mie", "Tartine", "Sandwich", "Croque-monsieur", "Kebab", "Burrito", "Nachos",
    "Frites", "Chips", "Nuggets", "Saucisse", "Merguez", "Jambon", "Saucisson", "Bacon",
    "Steak", "Poulet rôti", "Cuisse de poulet", "Côtelette", "Gigot", "Rôti", "Boulette", "Pot-au-feu",
    "Ratatouille", "Bœuf bourguignon", "Blanquette", "Cassoulet", "Choucroute", "Raclette", "Fondue", "Tartiflette",
    "Gratin", "Purée", "Soupe", "Omelette", "Œuf à la coque", "Camembert", "Gruyère", "Roquefort",
    "Mozzarella", "Yaourt", "Beurre", "Lait", "Crème chantilly", "Miel", "Confiture", "Pâte à tartiner",
    "Chocolat", "Bonbon", "Sucette", "Barbe à papa", "Guimauve", "Caramel", "Réglisse", "Chewing-gum",
    "Pomme d'amour", "Crème brûlée", "Mousse au chocolat", "Flan", "Tiramisu", "Profiterole", "Mille-feuille", "Paris-Brest",
    "Forêt-noire", "Clafoutis", "Crumble", "Sorbet", "Esquimau", "Milkshake", "Smoothie", "Jus d'orange",
    "Café", "Thé", "Chocolat chaud", "Limonade", "Soda", "Eau gazeuse", "Vin", "Bière",
    "Champagne", "Cocktail", "Cacahuète", "Noisette", "Noix", "Amande", "Pistache", "Châtaigne",
    "Olive", "Cornichon", "Ketchup", "Moutarde", "Mayonnaise", "Sel", "Poivre", "Sucre",
    "Farine", "Vinaigre", "Huile", "Moules-frites", "Saumon fumé", "Caviar", "Escargots de Bourgogne", "Cuisses de grenouille",
    "Foie gras", "Bretzel", "Bagel", "Pita", "Falafel", "Houmous", "Dim sum", "Nems",
    "Rouleau de printemps", "Ramen", "Pad thaï", "Curry", "Samoussa", "Tortilla", "Gaspacho", "Hachis parmentier",
    "Bouillabaisse", "Salade niçoise", "Tapenade", "Sauce tomate", "Tofu", "Maki", "Onigiri", "Brochette",
    "Croquette", "Panini", "Club sandwich", "Wrap", "Pâté", "Rillettes", "Terrine", "Calisson",
    "Nougat", "Praline", "Truffe", "Dragée", "Cannelle", "Vanille", "Cacao", "Céréales",
    "Muesli", "Porridge", "Biscotte", "Pain d'épices", "Kouign-amann", "Canelé", "Financier", "Far breton",
    "Baba au rhum", "Saint-Honoré", "Tarte Tatin", "Religieuse", "Meringue", "Île flottante", "Soufflé", "Croûton",
    "Grenadine", "Sirop", "Galette bretonne", "Pizza margherita", "Spaghettis bolognaise", "Carbonara", "Hamburger végétarien", "Fish and chips",
    "Poisson pané", "Bâtonnets de poisson", "Steak frites", "Œufs brouillés", "Pain perdu", "Tarte aux fraises", "Charlotte aux fraises", "Gâteau au chocolat",
    "Fondant au chocolat", "Cheesecake", "Donut au chocolat", "Barre chocolatée", "Tablette de chocolat", "Glace à la vanille", "Coupe de glace", "Banana split",
    "Melon d'eau", "Pop-corn caramel", "Biscuit", "Petit-beurre", "Galette", "Sablé", "Tuile aux amandes", "Langue de chat",
    "Fruits secs", "Raisins secs", "Pruneau", "Kumquat", "Goyave", "Physalis", "Carambole", "Fruit du dragon",
    "Durian", "Ramboutan", "Topinambour", "Panais", "Rutabaga", "Brocoli romanesco", "Chou rouge"
  ],
  "Objets": [
    "Parapluie", "Lunettes", "Ciseaux", "Ampoule", "Clé", "Bougie", "Horloge", "Ballon",
    "Valise", "Appareil photo", "Marteau", "Brosse à dents", "Échelle", "Cadenas", "Télescope", "Couronne",
    "Sablier", "Boussole", "Crayon", "Stylo", "Gomme", "Règle", "Taille-crayon", "Cahier",
    "Livre", "Cartable", "Trousse", "Agrafeuse", "Punaise", "Colle", "Pinceau", "Enveloppe",
    "Timbre", "Carte postale", "Calendrier", "Agenda", "Loupe", "Microscope", "Jumelles", "Lampe de poche",
    "Briquet", "Allumette", "Pile", "Aimant", "Montre", "Réveil", "Portefeuille", "Porte-monnaie",
    "Pièce de monnaie", "Billet de banque", "Carte bancaire", "Tirelire", "Sac à dos", "Sac à main", "Panier", "Seau",
    "Pelle", "Râteau", "Arrosoir", "Brouette", "Tournevis", "Clé à molette", "Pince", "Scie",
    "Perceuse", "Clou", "Vis", "Hache", "Corde", "Chaîne", "Cintre", "Pince à linge",
    "Épingle", "Aiguille", "Bobine de fil", "Dé à coudre", "Bouton", "Fermeture éclair", "Peigne", "Brosse à cheveux",
    "Sèche-cheveux", "Rasoir", "Miroir", "Parfum", "Rouge à lèvres", "Vernis à ongles", "Savon", "Dentifrice",
    "Éponge", "Serviette", "Mouchoir", "Coton-tige", "Pansement", "Thermomètre", "Seringue", "Béquille",
    "Fauteuil roulant", "Biberon", "Tétine", "Hochet", "Doudou", "Poupée", "Peluche", "Toupie",
    "Yoyo", "Cerf-volant", "Billes", "Dé", "Puzzle", "Jeu de cartes", "Domino", "Rubik's cube",
    "Pistolet à eau", "Balançoire", "Toboggan", "Bac à sable", "Château de sable", "Bulle de savon", "Ballon de baudruche", "Masque",
    "Éventail", "Ombrelle", "Canne", "Drapeau", "Trophée", "Médaille", "Coupe", "Ruban",
    "Cadeau", "Boîte", "Carton", "Caisse", "Coffre au trésor", "Bouteille", "Verre", "Tasse",
    "Bol", "Assiette", "Fourchette", "Couteau", "Cuillère", "Baguettes", "Paille", "Casserole",
    "Poêle", "Marmite", "Louche", "Fouet", "Rouleau à pâtisserie", "Passoire", "Râpe", "Tire-bouchon",
    "Ouvre-boîte", "Théière", "Cafetière", "Bouilloire", "Grille-pain", "Mixeur", "Thermos", "Gourde",
    "Planche à découper", "Saladier", "Plateau", "Nappe", "Bougeoir", "Chandelier", "Lanterne", "Lampe à huile",
    "Globe terrestre", "Carte au trésor", "Parchemin", "Plume", "Encrier", "Machine à écrire", "Tampon", "Badge",
    "Sifflet", "Mégaphone", "Cloche", "Clochette", "Sonnette", "Boîte aux lettres", "Poubelle", "Balai",
    "Serpillière", "Plumeau", "Ventilateur", "Radiateur", "Extincteur", "Hameçon", "Canne à pêche", "Tente",
    "Sac de couchage", "Hamac", "Parasol", "Bouée", "Masque de plongée", "Palmes", "Lunettes de soleil", "Crème solaire",
    "Glacière", "Boule à neige", "Boule de cristal", "Baguette magique", "Fer à cheval", "Pendule", "Cible", "Arc",
    "Flèche", "Bouclier", "Épée", "Armure", "Casque", "Catapulte", "Canon", "Dynamite",
    "Menottes", "Empreinte digitale", "Cage", "Niche", "Laisse", "Gamelle", "Aquarium", "Pipe",
    "Origami", "Ticket", "Passeport", "Carte d'identité", "Cadre photo", "Tableau noir", "Craie", "Feutre",
    "Crayon de couleur", "Compas", "Équerre", "Rapporteur", "Ardoise", "Classeur", "Post-it", "Ficelle",
    "Scotch", "Cutter", "Paquet", "Pâte à modeler", "Kaléidoscope", "Sac en papier", "Sac plastique", "Bocal en verre",
    "Pot de peinture", "Bombe de peinture", "Pistolet à colle", "Mètre ruban", "Niveau à bulle", "Lampe frontale", "Couteau suisse", "Boîte à outils",
    "Trousse de secours", "Cotons", "Lime à ongles", "Pince à épiler", "Brosse", "Fil de fer", "Cadenas à code", "Trousseau de clés",
    "Porte-documents", "Mallette", "Cabas", "Sacoche", "Caddie", "Tabouret pliant", "Chaise longue", "Transat",
    "Bâton de marche", "Bouteille à la mer", "Message secret", "Loupe de détective", "Mouchoir en papier", "Rouleau de scotch", "Gobelet", "Mug",
    "Flûte à champagne", "Carafe d'eau", "Saladier en bois", "Coquetier", "Pince à sucre", "Cuillère en bois", "Spatule", "Écumoire",
    "Presse-ail", "Épluche-légumes", "Moule à gâteau", "Emporte-pièce", "Sac à dos de randonnée", "Ceinture de sécurité pour bébé", "Lit parapluie", "Siège auto",
    "Poussette canne", "Cuvette", "Bassine", "Jerrican", "Tuyau d'arrosage", "Sécateur", "Binette", "Fourche",
    "Truelle", "Brosse métallique", "Pinceau plat", "Palette", "Chevalet de peintre", "Lampe à lave", "Quille", "Sac isotherme",
    "Bouillotte", "Chronomètre", "Coffret à bijoux", "Boîte à chaussures", "Pistolet à bulles", "Lance-pierre", "Sarbacane", "Marionnette à doigt"
  ],
  "Maison": [
    "Chaise", "Table", "Lit", "Canapé", "Fauteuil", "Armoire", "Commode", "Étagère",
    "Bureau", "Tabouret", "Banc", "Lit superposé", "Berceau", "Matelas", "Oreiller", "Couette",
    "Drap", "Coussin", "Tapis", "Rideau", "Store", "Lampe", "Lustre", "Abat-jour",
    "Lampadaire", "Interrupteur", "Prise électrique", "Fenêtre", "Porte", "Volet", "Poignée de porte", "Serrure",
    "Paillasson", "Escalier", "Rampe", "Ascenseur", "Cheminée", "Toit", "Grenier", "Cave",
    "Garage", "Balcon", "Terrasse", "Véranda", "Jardin", "Potager", "Clôture", "Portail",
    "Haie", "Pelouse", "Tondeuse", "Barbecue", "Salon de jardin", "Nain de jardin", "Cabane", "Salle de bain",
    "Baignoire", "Douche", "Lavabo", "Robinet", "Toilettes", "Papier toilette", "Chasse d'eau", "Tapis de bain",
    "Peignoir", "Cuisine", "Frigo", "Congélateur", "Four", "Micro-ondes", "Cuisinière", "Plaque de cuisson",
    "Hotte", "Évier", "Lave-vaisselle", "Lave-linge", "Sèche-linge", "Étendoir", "Panier à linge", "Fer à repasser",
    "Table à repasser", "Aspirateur", "Chauffe-eau", "Thermostat", "Climatiseur", "Horloge coucou", "Tableau", "Vase",
    "Pot de fleurs", "Plante verte", "Porte-manteau", "Placard", "Tiroir", "Dressing", "Coffre-fort", "Interphone",
    "Digicode", "Alarme", "Détecteur de fumée", "Établi", "Escabeau", "Rouleau de peinture", "Papier peint", "Carrelage",
    "Parquet", "Moquette", "Plafond", "Mur", "Brique", "Tuile", "Gouttière", "Antenne",
    "Parabole", "Panneau solaire", "Bûche", "Poêle à bois", "Lit à baldaquin", "Rocking-chair", "Pouf", "Table de chevet",
    "Veilleuse", "Coffre à jouets", "Paravent", "Litière", "Arbre à chat", "Bocal", "Boîte à biscuits", "Corbeille à fruits",
    "Sucrier", "Salière", "Poivrière", "Moulin à poivre", "Carafe", "Pichet", "Dessous de plat", "Set de table",
    "Torchon", "Tablier", "Gant de cuisine", "Minuteur", "Balance", "Cocotte-minute", "Friteuse", "Gaufrier",
    "Appareil à raclette", "Machine à café", "Presse-agrumes", "Essoreuse à salade", "Égouttoir", "Liquide vaisselle", "Sac poubelle", "Compost",
    "Salle à manger", "Chambre", "Chambre d'enfant", "Salon", "Couloir", "Entrée", "Buanderie", "Mezzanine",
    "Sous-sol", "Lucarne", "Velux", "Baie vitrée", "Porte-fenêtre", "Porte de garage", "Sonnette de porte", "Judas",
    "Verrou", "Chaîne de sûreté", "Boîte à clés", "Vide-poche", "Porte-parapluie", "Meuble à chaussures", "Banc d'entrée", "Console",
    "Table basse", "Meuble télé", "Bibliothèque murale", "Bureau d'écolier", "Chaise de bureau", "Lampe de bureau", "Corbeille à papier", "Lit d'enfant",
    "Matelas gonflable", "Futon", "Hamac de jardin", "Balancelle", "Parasol de jardin", "Piscine gonflable", "Trampoline de jardin", "Cabane dans les arbres",
    "Bac à fleurs", "Jardinière", "Mangeoire à oiseaux", "Nichoir", "Épouvantail de jardin", "Arrosage automatique", "Puits de jardin", "Fontaine de jardin",
    "Bassin à poissons", "Tas de bois", "Remise", "Abri de jardin", "Barrière", "Chatière", "Lit pour chien", "Coussin pour chat",
    "Cage à oiseaux", "Clapier", "Poulailler de jardin", "Lampe de chevet", "Porte-serviettes", "Rideau de douche", "Pommeau de douche", "Armoire à pharmacie",
    "Sèche-serviettes", "Tisonnier", "Panier à bûches", "Méridienne", "Banquette", "Îlot central", "Plan de travail", "Poubelle à pédale",
    "Bac de tri", "Porte-savon", "Distributeur de savon", "Ventouse", "Boîte à mouchoirs", "Pouf poire", "Tapis persan", "Tableau de liège",
    "Horloge murale", "Store vénitien", "Moustiquaire"
  ],
  "Lieux": [
    "Plage", "Hôpital", "Aéroport", "Bibliothèque", "Cinéma", "Piscine", "Boulangerie", "Château",
    "Église", "Gare", "Phare", "Zoo", "Musée", "Prison", "Stade", "Cirque",
    "Supermarché", "École", "Tour Eiffel", "Île déserte", "Camping", "Ferme", "Pyramide", "Collège",
    "Lycée", "Université", "Mairie", "Bureau de poste", "Banque", "Commissariat", "Caserne de pompiers", "Pharmacie",
    "Boucherie", "Poissonnerie", "Fromagerie", "Épicerie", "Marché", "Centre commercial", "Magasin de jouets", "Fleuriste",
    "Librairie", "Salon de coiffure", "Restaurant", "Bistrot", "Bar", "Pizzeria", "Fast-food", "Crêperie",
    "Hôtel", "Auberge", "Théâtre", "Opéra", "Salle de concert", "Discothèque", "Patinoire", "Gymnase",
    "Parc", "Aire de jeux", "Parc d'attractions", "Fête foraine", "Planétarium", "Observatoire", "Laboratoire", "Usine",
    "Chantier", "Port", "Quai", "Pont", "Tunnel", "Autoroute", "Rond-point", "Carrefour",
    "Parking", "Station-service", "Station de métro", "Arrêt de bus", "Gratte-ciel", "Immeuble", "Maison", "Igloo",
    "Tipi", "Yourte", "Chalet", "Moulin", "Moulin à vent", "Grange", "Écurie", "Poulailler",
    "Porcherie", "Étable", "Serre", "Verger", "Vignoble", "Champ", "Cimetière", "Cathédrale",
    "Mosquée", "Temple", "Synagogue", "Chapelle", "Monastère", "Abbaye", "Fort", "Forteresse",
    "Donjon", "Ruines", "Arc de triomphe", "Colisée", "Statue de la Liberté", "Big Ben", "Tour de Pise", "Muraille de Chine",
    "Taj Mahal", "Mont Saint-Michel", "Sphinx", "Stonehenge", "Machu Picchu", "Opéra de Sydney", "Château de Versailles", "Notre-Dame",
    "Venise", "Paris", "Londres", "New York", "Rome", "Tokyo", "Égypte", "Japon",
    "Chine", "Inde", "Mexique", "Brésil", "Canada", "Australie", "Afrique", "Pôle Nord",
    "Pôle Sud", "Antarctique", "Station spatiale", "Base secrète", "Île au trésor", "Station de ski", "Piste de ski", "Refuge",
    "Cour de récréation", "Salle de classe", "Cantine", "Infirmerie", "Salle d'attente", "Bloc opératoire", "Urgences", "Maternité",
    "Maison de retraite", "Crèche", "Tribunal", "Parlement", "Ambassade", "Palais", "Manoir", "Maison hantée",
    "Labyrinthe", "Mine", "Carrière", "Barrage", "Centrale nucléaire", "Puits", "Fontaine", "Lavoir",
    "Kiosque", "Cabine téléphonique", "Toilettes publiques", "Laverie", "Salle de sport", "Spa", "Sauna", "Hammam",
    "Ranch", "Saloon", "Plateforme pétrolière", "Écluse", "Marina", "Plongeoir", "Toboggan aquatique", "Parc aquatique",
    "Terrain de foot", "Court de tennis", "Ring de boxe", "Hippodrome", "Circuit automobile", "Vélodrome", "Arène", "Casino",
    "Open space", "Salle de réunion", "Vestiaire", "Douane", "Frontière", "Péage", "Village", "Ville",
    "Capitale", "Banlieue", "Campagne", "Rue", "Ruelle", "Place du village", "Square", "Jardin public",
    "Bergerie", "Château fort", "Tour de contrôle", "Aire d'autoroute", "Gare routière", "Port de pêche", "Chantier naval", "Entrepôt",
    "Bureau de vote", "Salle des fêtes", "Médiathèque", "Ludothèque", "Conservatoire", "Atelier", "Garage automobile", "Concession automobile",
    "Agence de voyage", "Bijouterie", "Boutique de vêtements", "Cordonnerie", "Quincaillerie", "Animalerie", "Jardinerie", "Pressing",
    "Tabac", "Kebab du coin", "Salon de thé", "Glacier", "Chocolaterie", "Brasserie", "Cave à vin", "Distillerie",
    "Cabinet médical", "Cabinet dentaire", "Clinique vétérinaire", "Centre de loisirs", "Colonie de vacances", "Auberge de jeunesse", "Base de loisirs", "Zoo safari",
    "Réserve naturelle", "Parc national", "Belvédère", "Téléski", "Port de plaisance", "Bord de mer", "Front de mer", "Promenade",
    "Jetée", "Ponton", "Cabane de pêcheur", "Cabine de plage", "Paillote", "Club de vacances", "Pont suspendu", "Pont-levis",
    "Viaduc", "Aqueduc", "Tour de guet", "Remparts", "Douves", "Oubliettes", "Salle du trône", "Catacombes",
    "Égouts", "Volière", "Vivarium", "Ferme pédagogique", "Pagode", "Temple grec", "Temple maya", "Acropole",
    "Pétra", "Chutes du Niagara", "Mont Everest", "Mont Fuji", "Kilimandjaro", "Sahara", "Amazonie", "Himalaya",
    "Alpes", "Hollywood", "Las Vegas", "Laponie", "Hawaï", "Islande", "Groenland", "Madagascar",
    "Tahiti", "Sibérie"
  ],
  "Métiers": [
    "Pompier", "Astronaute", "Cuisinier", "Médecin", "Policier", "Magicien", "Clown", "Plongeur",
    "Peintre", "Jardinier", "Boxeur", "Pilote", "Facteur", "Dentiste", "Cow-boy", "Musicien",
    "Photographe", "Infirmier", "Chirurgien", "Vétérinaire", "Pharmacien", "Kinésithérapeute", "Opticien", "Sage-femme",
    "Ambulancier", "Professeur", "Maîtresse d'école", "Directeur d'école", "Bibliothécaire", "Chercheur", "Scientifique", "Archéologue",
    "Paléontologue", "Astronome", "Inventeur", "Ingénieur", "Architecte", "Informaticien", "Développeur", "Hacker",
    "Youtubeur", "Influenceur", "Journaliste", "Présentateur télé", "Présentateur météo", "Reporter", "Écrivain", "Poète",
    "Traducteur", "Acteur", "Réalisateur", "Cascadeur", "Chanteur", "DJ", "Danseur", "Danseuse étoile",
    "Mannequin", "Styliste", "Couturier", "Coiffeur", "Maquilleur", "Esthéticienne", "Tatoueur", "Barbier",
    "Boulanger", "Pâtissier", "Boucher", "Poissonnier", "Fromager", "Chocolatier", "Serveur", "Barman",
    "Sommelier", "Caissier", "Vendeur", "Livreur", "Chauffeur de taxi", "Chauffeur de bus", "Routier", "Conducteur de train",
    "Contrôleur", "Hôtesse de l'air", "Capitaine", "Marin", "Pêcheur", "Agriculteur", "Fermier", "Berger",
    "Apiculteur", "Vigneron", "Bûcheron", "Garde forestier", "Maçon", "Charpentier", "Menuisier", "Plombier",
    "Électricien", "Peintre en bâtiment", "Couvreur", "Serrurier", "Mécanicien", "Garagiste", "Soudeur", "Forgeron",
    "Horloger", "Bijoutier", "Cordonnier", "Tailleur", "Paysagiste", "Éboueur", "Balayeur", "Concierge",
    "Gardien", "Agent de sécurité", "Garde du corps", "Détective", "Espion", "Agent secret", "Gendarme", "Militaire",
    "Soldat", "Général", "Parachutiste", "Douanier", "Juge", "Avocat", "Notaire", "Maire",
    "Président", "Ministre", "Député", "Banquier", "Comptable", "Secrétaire", "Standardiste", "Réceptionniste",
    "Guide touristique", "Moniteur de ski", "Maître-nageur", "Sauveteur", "Entraîneur", "Arbitre", "Footballeur", "Tennisman",
    "Jockey", "Pilote de course", "Torero", "Dresseur", "Dompteur", "Jongleur", "Acrobate", "Trapéziste",
    "Funambule", "Mime", "Marionnettiste", "Ventriloque", "Cracheur de feu", "Ramoneur", "Laitier", "Vitrier",
    "Grutier", "Déménageur", "Mineur", "Sculpteur", "Potier", "Souffleur de verre", "Dessinateur", "Illustrateur",
    "Graphiste", "Caricaturiste", "Chef d'orchestre", "Pianiste", "Violoniste", "Batteur", "Guitariste", "Rappeur",
    "Humoriste", "Ostéopathe", "Psychologue", "Laborantin", "Pédiatre", "Moine", "Prêtre", "Bonne sœur",
    "Pape", "Explorateur", "Aventurier", "Alpiniste", "Spéléologue", "Navigateur", "Gardien de zoo", "Soigneur animalier",
    "Toiletteur", "Maréchal-ferrant", "Chasseur", "Trappeur", "Croupier", "Pizzaïolo", "Crêpier", "Charcutier",
    "Épicier", "Libraire", "Antiquaire", "Brocanteur", "Commissaire-priseur", "Agent immobilier", "Coursier", "Contrôleur aérien",
    "Hôtesse d'accueil", "Nounou", "Baby-sitter", "Animateur", "Éducateur", "Surveillant", "Moniteur d'auto-école", "Pompiste",
    "Chef cuisinier", "Plongeur de restaurant", "Femme de ménage", "Majordome", "Valet", "Groom", "Portier", "Videur",
    "Agent de circulation", "Policier à cheval", "Pompier forestier", "Gardien de phare", "Gardien de musée", "Gardien de prison", "Commissaire", "Inspecteur",
    "Médecin légiste", "Urgentiste", "Infirmière scolaire", "Orthodontiste", "Diététicien", "Coach sportif", "Professeur de yoga", "Professeur de danse",
    "Professeur de musique", "Chef de chantier", "Conducteur d'engin", "Couturière", "Fleuriste de mariage", "Wedding planner", "Traiteur", "Boulanger de nuit",
    "Livreur de pizza", "Chauffeur de camion-poubelle", "Agent de nettoyage", "Vigile", "Pilote d'hélicoptère", "Pilote de chasse", "Astronome amateur", "Biologiste",
    "Chimiste", "Physicien", "Mathématicien", "Géologue", "Volcanologue", "Océanographe", "Météorologue", "Botaniste",
    "Zoologiste", "Entomologiste", "Historien", "Guide de montagne", "Fauconnier", "Animateur radio", "Projectionniste", "Machiniste",
    "Ingénieur du son", "Perchman", "Caméraman", "Pilote de drone", "Démineur", "Bagagiste", "Garde-côte", "Sauveteur en mer",
    "Brancardier", "Secouriste", "Aide-soignant", "Vendeur de glaces", "Marchand de journaux", "Crieur public", "Allumeur de réverbères", "Chevrier",
    "Porcher", "Vacher", "Tonnelier", "Luthier", "Accordeur de piano"
  ],
  "Sports & loisirs": [
    "Football", "Tennis", "Ski", "Surf", "Basket", "Bowling", "Golf", "Natation",
    "Escalade", "Karaté", "Échecs", "Skateboard", "Plongée", "Équitation", "Danse", "Cyclisme",
    "Tir à l'arc", "Ping-pong", "Yoga", "Rugby", "Handball", "Volley-ball", "Beach-volley", "Baseball",
    "Hockey sur glace", "Hockey sur gazon", "Badminton", "Squash", "Boxe", "Judo", "Taekwondo", "Kung-fu",
    "Lutte", "Sumo", "Escrime", "Haltérophilie", "Musculation", "Gymnastique", "Trampoline", "Saut à la perche",
    "Saut en longueur", "Saut en hauteur", "Lancer du javelot", "Lancer du poids", "Lancer du disque", "Marathon", "Course à pied", "Sprint",
    "Course de haies", "Relais", "Triathlon", "Biathlon", "Patinage artistique", "Patin à glace", "Roller", "Luge",
    "Bobsleigh", "Snowboard", "Ski de fond", "Saut à ski", "Curling", "Raquettes à neige", "Alpinisme", "Randonnée",
    "Parapente", "Parachutisme", "Deltaplane", "Saut à l'élastique", "Kitesurf", "Planche à voile", "Ski nautique", "Wakeboard",
    "Aviron", "Canoë", "Kayak", "Rafting", "Water-polo", "Plongeon", "Natation synchronisée", "Voile",
    "Motocross", "Formule 1", "Rallye", "Karting", "BMX", "VTT", "Pétanque", "Billard",
    "Fléchettes", "Mini-golf", "Babyfoot", "Flipper", "Jeu vidéo", "Dames", "Poker", "Mots croisés",
    "Sudoku", "Tricot", "Couture", "Crochet", "Broderie", "Poterie", "Peinture", "Dessin",
    "Jardinage", "Bricolage", "Lecture", "Photographie", "Karaoké", "Jonglage", "Frisbee", "Corde à sauter",
    "Marelle", "Cache-cache", "Chat perché", "Colin-maillard", "Chaises musicales", "Tir à la corde", "Course en sac", "Balle au prisonnier",
    "Saute-mouton", "Pierre-feuille-ciseaux", "Bataille de polochons", "Bataille de boules de neige", "Pique-nique", "Chasse au trésor", "Escape game", "Paintball",
    "Laser game", "Accrobranche", "Tyrolienne", "Spéléologie", "Polo", "Zumba", "Aérobic", "Pilates",
    "Méditation", "Tai-chi", "Boomerang", "Haltères", "Tapis de course", "Vélo d'appartement", "Ballon de foot", "Ballon de rugby",
    "Raquette", "Volant de badminton", "Crosse de hockey", "Batte de baseball", "Gant de boxe", "Podium", "Médaille d'or", "Coupe du monde",
    "Jeux olympiques", "Flamme olympique", "Carton rouge", "Penalty", "But", "Panier de basket", "Filet", "Patins à roulettes",
    "Hoverboard", "Échasses", "Hula hoop", "Diabolo", "Bilboquet", "Osselets", "Modélisme", "Train électrique",
    "Voiture télécommandée", "Aquagym", "Apnée", "Course d'orientation", "Danse classique", "Hip-hop", "Breakdance", "Salsa",
    "Tango", "Valse", "Claquettes", "Ballet", "French cancan", "Moonwalk", "Football américain", "Cricket",
    "Softball", "Ultimate", "Pelote basque", "Lacrosse", "Kick-boxing", "Capoeira", "Aïkido", "Sabre",
    "Fleuret", "Tir sportif", "Ball-trap", "Course de chevaux", "Saut d'obstacles", "Dressage", "Rodéo", "Course de lévriers",
    "Course de dragsters", "Moto GP", "Vol à voile", "ULM", "Montgolfière de loisir", "Plongée en apnée", "Chasse sous-marine", "Bodyboard",
    "Stand-up paddle", "Char à voile", "Luge d'été", "Slackline", "Parkour", "Trottinette freestyle", "Patinage de vitesse", "Ski alpin",
    "Slalom", "Biathlon d'été", "Marche nordique", "Course de côte", "Spinning", "Crossfit", "Step", "Gainage",
    "Pompes", "Abdos", "Étirements", "Équilibre", "Roue arrière", "Saut périlleux", "Grand écart", "Poirier",
    "Roue", "Pyramide humaine", "Barres parallèles", "Anneaux", "Cheval d'arçons", "Poutre", "Ruban de gymnastique", "Massue",
    "Cerceau", "Canyoning", "Via ferrata", "Ski de randonnée", "Kin-ball", "Quilles", "Croquet", "Palet",
    "Mölkky", "Jeu de l'oie", "Petits chevaux", "Mikado", "Bataille navale", "Morpion", "Pendu", "Memory",
    "Jeu de rôle", "Charades", "Devinettes", "Kendo", "Muay-thaï", "Lancer du marteau", "Steeple", "Marche athlétique",
    "Cross-country", "Trail"
  ],
  "Nature": [
    "Arc-en-ciel", "Cactus", "Tornade", "Soleil", "Lune", "Éclair", "Cascade", "Palmier",
    "Flocon de neige", "Tournesol", "Nuage", "Étoile filante", "Rose", "Champignon", "Vague", "Sapin",
    "Feuille", "Coquillage", "Grotte", "Rivière", "Montagne", "Désert", "Volcan", "Jungle",
    "Savane", "Prairie", "Oasis", "Forêt", "Lac", "Étang", "Mare", "Marais",
    "Océan", "Mer", "Île", "Falaise", "Colline", "Vallée", "Canyon", "Iceberg",
    "Banquise", "Geyser", "Source", "Ruisseau", "Fleuve", "Dune", "Récif de corail", "Lagon",
    "Marée", "Tsunami", "Ouragan", "Tempête", "Orage", "Pluie", "Grêle", "Neige",
    "Brouillard", "Givre", "Rosée", "Verglas", "Avalanche", "Tremblement de terre", "Éruption", "Lave",
    "Inondation", "Sécheresse", "Vent", "Aurore boréale", "Coucher de soleil", "Lever de soleil", "Éclipse", "Étoile",
    "Constellation", "Planète", "Comète", "Météorite", "Galaxie", "Voie lactée", "Trou noir", "Ciel étoilé",
    "Arbre", "Chêne", "Saule pleureur", "Bouleau", "Érable", "Baobab", "Bambou", "Bonsaï",
    "Cocotier", "Pin", "Olivier", "Pommier", "Cerisier en fleurs", "Racine", "Tronc", "Branche",
    "Écorce", "Bourgeon", "Pomme de pin", "Gland", "Marron", "Fleur", "Tulipe", "Marguerite",
    "Pâquerette", "Coquelicot", "Lys", "Orchidée", "Lavande", "Muguet", "Jonquille", "Pissenlit",
    "Violette", "Lotus", "Nénuphar", "Bleuet", "Hortensia", "Trèfle", "Trèfle à quatre feuilles", "Herbe",
    "Fougère", "Lierre", "Liane", "Algue", "Roseau", "Ortie", "Chardon", "Houx",
    "Gui", "Plante carnivore", "Graine", "Pousse", "Épi de blé", "Botte de foin", "Rocher", "Caillou",
    "Galet", "Sable", "Boue", "Flaque d'eau", "Cristal", "Diamant", "Pépite d'or", "Fossile",
    "Terre", "Feu", "Fumée", "Glaçon", "Goutte d'eau", "Bonhomme de neige", "Boule de neige", "Stalactite",
    "Toile d'araignée", "Nid d'oiseau", "Ruche", "Fourmilière", "Terrier", "Barrage de castors", "Empreinte de pas", "Printemps",
    "Été", "Automne", "Hiver", "Pleine lune", "Croissant de lune", "Ombre", "Horizon", "Mirage",
    "Sommet", "Plaine", "Steppe", "Toundra", "Mangrove", "Forêt tropicale", "Clairière", "Sentier",
    "Chemin", "Berge", "Tourbillon", "Écume", "Rayon de soleil", "Ciel nuageux", "Nuage de pluie", "Arc de pierre",
    "Rocher en équilibre", "Grain de sable", "Coquille d'escargot", "Perle", "Nacre", "Rubis", "Émeraude", "Saphir",
    "Améthyste", "Quartz", "Charbon", "Pétrole", "Magma", "Cratère", "Fumerolle", "Source chaude",
    "Lac gelé", "Cascade gelée", "Bouleau blanc", "Séquoia", "Cyprès", "Magnolia", "Glycine", "Jasmin",
    "Chrysanthème", "Pivoine", "Géranium", "Iris", "Camélia", "Edelweiss", "Dent-de-lion", "Mimosa",
    "Bruyère", "Genêt", "Ronce", "Buisson", "Feuille morte", "Tapis de feuilles", "Brindille", "Souche",
    "Mousse des bois", "Lichen", "Champignon vénéneux", "Cèpe", "Girolle", "Vent du nord", "Bourrasque", "Arc-en-ciel double",
    "Halo lunaire", "Nuit étoilée", "Crépuscule", "Aube", "Brume", "Nuage en forme de cœur", "Cumulonimbus", "Volcan sous-marin",
    "Cheminée de fée", "Fjord", "Gorge", "Delta", "Estuaire", "Presqu'île", "Archipel", "Atoll",
    "Baie", "Crique", "Cap", "Ravin", "Gouffre", "Crevasse", "Tourbière", "Bocage",
    "Lande", "Garrigue", "Maquis", "Pinède", "Palmeraie", "Rizière", "Champ de tournesols", "Champ de lavande",
    "Champ de blé", "Vigne", "Noyer", "Châtaignier", "Platane", "Tilleul", "Hêtre", "Mélèze",
    "Acacia", "Eucalyptus", "Figuier", "Citronnier", "Oranger", "Bananier", "Aloe vera", "Agave"
  ],
  "Transports": [
    "Vélo", "Fusée", "Voiture", "Camion", "Bus", "Tramway", "Métro", "Train",
    "TGV", "Locomotive à vapeur", "Wagon", "Moto", "Scooter", "Trottinette", "Trottinette électrique", "Monocycle",
    "Tandem", "Tricycle", "Taxi", "Limousine", "Décapotable", "Jeep", "Quatre-quatre", "Quad",
    "Buggy", "Camping-car", "Caravane", "Remorque", "Dépanneuse", "Camion de pompiers", "Ambulance", "Voiture de police",
    "Camion-poubelle", "Bétonnière", "Grue de chantier", "Bulldozer", "Pelleteuse", "Tracteur", "Moissonneuse-batteuse", "Rouleau compresseur",
    "Chariot élévateur", "Kart", "Voiture de course", "Monster truck", "Char d'assaut", "Avion", "Avion de chasse", "Avion en papier",
    "Planeur", "Hélicoptère", "Hydravion", "Montgolfière", "Dirigeable", "Jetpack", "Navette spatiale", "Soucoupe volante",
    "Satellite", "Parachute", "Bateau", "Voilier", "Paquebot", "Ferry", "Péniche", "Barque",
    "Pirogue", "Radeau", "Catamaran", "Yacht", "Hors-bord", "Jet-ski", "Sous-marin", "Bateau pirate",
    "Galion", "Drakkar", "Gondole", "Canot de sauvetage", "Pédalo", "Paddle", "Porte-avions", "Remorqueur",
    "Chalutier", "Brise-glace", "Aéroglisseur", "Téléphérique", "Télésiège", "Funiculaire", "Escalator", "Tapis roulant",
    "Calèche", "Carrosse", "Diligence", "Charrette", "Traîneau", "Traîneau à chiens", "Chariot", "Poussette",
    "Landau", "Gyroroue", "Rickshaw", "Tuk-tuk", "Pousse-pousse", "Bus scolaire", "Bus à impériale", "Camionnette",
    "Fourgon blindé", "Corbillard", "Food truck", "Camion de glaces", "Voiture électrique", "Panneau stop", "Feu rouge", "Passage piéton",
    "Volant", "Pneu", "Roue de secours", "Klaxon", "Rétroviseur", "Essuie-glace", "Ceinture de sécurité", "Casque de moto",
    "GPS", "Plaque d'immatriculation", "Ancre", "Gouvernail", "Hélice", "Bouée de sauvetage", "Hublot", "Mât",
    "Rame", "Pagaie", "Cockpit", "Piste d'atterrissage", "Carte d'embarquement", "Rails", "Passage à niveau", "Vélo électrique",
    "Vélo de course", "Vélo couché", "Vélo-cargo", "Draisienne", "Side-car", "Mobylette", "Chopper", "Motoneige",
    "Dameuse", "Chasse-neige", "Balayeuse", "Camion-citerne", "Semi-remorque", "Porte-voitures", "Bus articulé", "Navette d'aéroport",
    "Avion-cargo", "Avion à hélice", "Biplan", "Jumbo-jet", "Concorde", "Autogire", "Fusée à étages", "Capsule spatiale",
    "Module lunaire", "Voilier trois-mâts", "Caravelle", "Trirème", "Kayak de mer", "Bateau-mouche", "Vedette", "Bateau de pêche",
    "Bateau gonflable", "Zodiac", "Bathyscaphe", "Locomotive diesel", "Train de marchandises", "Train de nuit", "Train à crémaillère", "Monorail",
    "Draisine", "Wagon-restaurant", "Wagon-lit", "Cabriolet", "Voiture de collection", "Voiture sans permis", "Voiturette de golf", "Voiture à pédales",
    "Fourgon de police", "Bateau de croisière", "Cargo", "Porte-conteneurs", "Pétrolier", "Char romain", "Char à bœufs", "Traîneau du Père Noël",
    "Tondeuse autoportée", "Voiture de rallye", "Dragster", "Camion de déménagement", "Wagonnet"
  ],
  "Vêtements & accessoires": [
    "Chapeau", "Casquette", "Bonnet", "Béret", "Chapeau de paille", "Haut-de-forme", "Sombrero", "Chapeau de cow-boy",
    "Bob", "Cagoule", "Écharpe", "Foulard", "Cravate", "Nœud papillon", "Gants", "Moufles",
    "Chaussettes", "Collants", "Chaussures", "Baskets", "Bottes", "Bottes de pluie", "Sandales", "Tongs",
    "Chaussons", "Pantoufles", "Talons hauts", "Escarpins", "Mocassins", "Sabots", "T-shirt", "Chemise",
    "Pull", "Sweat à capuche", "Gilet", "Veste", "Blouson", "Manteau", "Doudoune", "Imperméable",
    "Cape", "Poncho", "Smoking", "Costume", "Robe", "Robe de mariée", "Jupe", "Tutu",
    "Short", "Pantalon", "Jean", "Salopette", "Combinaison", "Pyjama", "Chemise de nuit", "Robe de chambre",
    "Maillot de bain", "Bikini", "Slip", "Caleçon", "Soutien-gorge", "Culotte", "Bermuda", "Kilt",
    "Kimono", "Sari", "Toge", "Blouse", "Uniforme", "Combinaison de ski", "Combinaison spatiale", "Scaphandre",
    "Gilet de sauvetage", "Gilet jaune", "Ceinture", "Bretelles", "Sac banane", "Bracelet", "Collier", "Bague",
    "Boucles d'oreilles", "Broche", "Pendentif", "Médaillon", "Diadème", "Tiare", "Serre-tête", "Barrette",
    "Chouchou", "Perruque", "Moustache", "Barbe", "Monocle", "Cache-œil", "Pochette", "Casque de chantier",
    "Casque de vélo", "Bonnet de bain", "Lunettes de piscine", "Bavoir", "Couche", "Grenouillère", "Chaussons de danse", "Justaucorps",
    "Jambières", "Genouillères", "Protège-dents", "Lacet", "Semelle", "Poche", "Col roulé", "Manche",
    "Capuche", "Écusson", "Paillettes", "Mitaines", "Cache-oreilles", "Turban", "Fez", "Chapka",
    "Bandana", "Bandeau", "Casque viking", "Couronne de fleurs", "Collier de fleurs", "Déguisement", "Porte-clés", "Crampons",
    "Treillis", "Chapeau melon", "Canotier", "Panama", "Bonnet à pompon", "Béret basque", "Casquette à l'envers", "Visière",
    "Chapeau de pirate", "Chapeau de sorcière", "Chapeau de chef", "Toque de cuisinier", "Casque de pompier", "Képi", "Bicorne", "Bonnet de nuit",
    "Écharpe de supporter", "Cravate à pois", "Lavallière", "Jabot", "Gants de ski", "Gants de jardinage", "Chaussettes dépareillées", "Chaussures de ski",
    "Chaussures de randonnée", "Bottes de cow-boy", "Bottines", "Espadrilles", "Derbies", "Ballerines", "Claquettes de piscine", "Chaussures à crampons",
    "Rollers", "Pull de Noël", "Marinière", "Débardeur", "Polo de golf", "Chemise hawaïenne", "Chemise à carreaux", "Veste en jean",
    "Veste en cuir", "Trench", "Caban", "Parka", "Coupe-vent", "Smoking blanc", "Queue-de-pie", "Gilet de costume",
    "Robe de soirée", "Robe d'été", "Minijupe", "Jupe plissée", "Pantalon à pattes d'éléphant", "Jogging", "Survêtement", "Legging",
    "Short de bain", "Combinaison de plongée", "Tenue de karaté", "Kimono de judo", "Tablier de cuisine", "Blouse de chimiste", "Tenue de chirurgien", "Combinaison d'apiculteur",
    "Armure de chevalier", "Cotte de mailles", "Sac à dos d'écolier", "Banane de sport", "Lunettes rondes", "Lunettes de vue", "Lunettes de ski", "Montre à gousset",
    "Gourmette", "Chevalière", "Piercing au nez", "Boucle de ceinture", "Bretelles rouges", "Blouson d'aviateur", "Bonnet péruvien", "Ceinture noire",
    "Pince à cravate", "Boutons de manchette", "Gilet pare-balles", "Cape de super-héros", "Masque de super-héros", "Babouches", "Mules", "Chaussures lumineuses",
    "Lunettes d'aviateur", "Moon boots", "Chapeau chinois"
  ],
  "Corps & santé": [
    "Main", "Pied", "Bras", "Jambe", "Tête", "Œil", "Nez", "Bouche",
    "Oreille", "Dent", "Langue", "Lèvres", "Cheveux", "Sourcil", "Cil", "Front",
    "Joue", "Menton", "Cou", "Épaule", "Coude", "Poignet", "Doigt", "Pouce",
    "Ongle", "Genou", "Cheville", "Orteil", "Talon", "Dos", "Ventre", "Nombril",
    "Fesses", "Cœur", "Cerveau", "Poumons", "Estomac", "Rein", "Squelette", "Crâne",
    "Os", "Colonne vertébrale", "Muscle", "Biceps", "Veine", "Sang", "Peau", "Grain de beauté",
    "Tache de rousseur", "Ride", "Fossette", "Tatouage", "Piercing", "Cicatrice", "Bosse", "Rhume",
    "Fièvre", "Toux", "Éternuement", "Hoquet", "Bâillement", "Mal de dents", "Mal de tête", "Jambe cassée",
    "Plâtre", "Bandage", "Attelle", "Vaccin", "Pilule", "Médicament", "Stéthoscope", "Radiographie",
    "Brancard", "Dentier", "Appareil dentaire", "Appareil auditif", "ADN", "Microbe", "Virus", "Bactérie",
    "Sourire", "Clin d'œil", "Grimace", "Larme", "Ronflement", "Somnambule", "Cauchemar", "Rêve",
    "Abdominaux", "Poing", "Câlin", "Bisou", "Bébé", "Jumeaux", "Femme enceinte", "Chauve",
    "Queue de cheval", "Tresse", "Chignon", "Coupe afro", "Crête iroquoise", "Dreadlocks", "Bigoudis", "Empreinte de main",
    "Main tendue", "Pouce levé", "Poignée de main", "Bras de fer", "Coup de soleil", "Piqûre de moustique", "Ampoule au pied", "Œil au beurre noir",
    "Nez qui coule", "Dent de lait", "Dent cassée", "Carie", "Brosse à dents électrique", "Fil dentaire", "Bain de bouche", "Gélule",
    "Comprimé effervescent", "Pommade", "Gouttes pour les yeux", "Inhalateur", "Masque chirurgical", "Gants médicaux", "Tensiomètre", "Lit médicalisé",
    "Perfusion", "Électrocardiogramme", "IRM", "Scanner médical", "Fauteuil de dentiste", "Lunettes de lecture", "Squelette de dinosaure", "Os de poulet",
    "Mâchoire", "Gencive", "Narine", "Paupière", "Pupille", "Lobe d'oreille", "Pomme d'Adam", "Aisselle",
    "Hanche", "Mollet", "Cuisse", "Plante des pieds", "Sourire édenté", "Moustache en guidon", "Barbe de trois jours", "Cheveux en pétard",
    "Bras cassé", "Nez rouge", "Oreilles décollées", "Joues rouges", "Ventre rond", "Pieds nus", "Ongles vernis", "Cheveux bouclés",
    "Cheveux longs"
  ],
  "Personnages & fantastique": [
    "Pirate", "Chevalier", "Sorcière", "Princesse", "Prince", "Roi", "Reine", "Fée",
    "Elfe", "Lutin", "Nain", "Géant", "Ogre", "Troll", "Gobelin", "Dragon",
    "Licorne", "Pégase", "Sirène", "Centaure", "Minotaure", "Cyclope", "Phénix", "Griffon",
    "Hydre", "Kraken", "Yéti", "Monstre du Loch Ness", "Vampire", "Loup-garou", "Zombie", "Momie",
    "Fantôme", "Frankenstein", "Démon", "Diable", "Ange", "Sorcier", "Druide", "Génie",
    "Lampe magique", "Tapis volant", "Chaudron", "Balai de sorcière", "Potion magique", "Grimoire", "Super-héros", "Super-vilain",
    "Robot", "Extraterrestre", "Martien", "Cyborg", "Ninja", "Samouraï", "Viking", "Gladiateur",
    "Mousquetaire", "Shérif", "Bandit", "Cambrioleur", "Voleur", "Robin des Bois", "Zorro", "Père Noël",
    "Fée Clochette", "Petit Chaperon rouge", "Grand méchant loup", "Trois petits cochons", "Blanche-Neige", "Cendrillon", "Belle au bois dormant", "Raiponce",
    "Pinocchio", "Peter Pan", "Capitaine Crochet", "Alice au pays des merveilles", "Lapin blanc", "Chapelier fou", "Petit Poucet", "Hansel et Gretel",
    "Barbe bleue", "Chat botté", "Aladdin", "Ali Baba", "Sinbad", "Hercule", "Zeus", "Poséidon",
    "Hadès", "Cupidon", "Thor", "Pharaon", "Cléopâtre", "Napoléon", "Jules César", "Christophe Colomb",
    "Einstein", "Dracula", "Sherlock Holmes", "Tarzan", "Mowgli", "Gulliver", "Don Quichotte", "Le Petit Prince",
    "Bonhomme en pain d'épice", "Épouvantail", "Marionnette", "Arlequin", "Pierrot", "Bouffon", "Ménestrel", "Écuyer",
    "Seigneur", "Gnome", "Farfadet", "Korrigan", "Golem", "Gargouille", "Chimère", "Anubis",
    "Cerbère", "Hippogriffe", "Dragon chinois", "Nymphe", "Petite souris", "Croque-mitaine", "Marchand de sable", "Lapin de Pâques",
    "Amazone", "Barbare", "Archer", "Roi Arthur", "Merlin l'enchanteur", "Excalibur", "Saint Graal", "Table ronde",
    "Trésor", "Jambe de bois", "Drapeau pirate", "Tête de mort", "Cercueil", "Pierre tombale", "Chat noir", "Œuf de dragon",
    "Trône", "Sceptre", "Reine des neiges", "OVNI", "Rayon laser", "Sabre laser", "Pistolet laser", "Téléporteur",
    "Machine à remonter le temps", "Portail magique", "Cape d'invisibilité", "Bottes de sept lieues", "Pantoufle de verre", "Pomme empoisonnée", "Miroir magique", "Haricot magique",
    "Poule aux œufs d'or", "Lapin dans un chapeau", "Pierre philosophale", "Fontaine de jouvence", "Atlantide", "Eldorado", "Sorcière sur son balai", "Fée marraine",
    "Prince charmant", "Princesse au petit pois", "Vilain petit canard", "Belle et la Bête", "Petite sirène", "Boucle d'or", "Trois ours", "Jack et le haricot magique",
    "Joueur de flûte", "Soldat de plomb", "Casse-noisette", "Baron de Münchhausen", "Robinson Crusoé", "Vendredi", "Long John Silver", "Capitaine Nemo",
    "Phileas Fogg", "Jules Verne", "Docteur Jekyll", "Homme invisible", "Fantôme de l'Opéra", "Quasimodo", "Esmeralda", "D'Artagnan",
    "Cyrano de Bergerac", "Lancelot", "Fée Morgane", "Dame du Lac", "Sorcier noir", "Roi des elfes", "Reine des fées", "Dragon à trois têtes",
    "Serpent de mer", "Licorne ailée", "Chat à neuf queues", "Ogre affamé", "Géant de pierre", "Homme de neige", "Bonhomme Hiver", "Chevalier sans tête",
    "Cavalier fantôme", "Lutin farceur", "Elfe de Noël", "Renne au nez rouge", "Fantôme de château", "Squelette pirate", "Momie égyptienne", "Vampire végétarien",
    "Zombie danseur", "Robot cuisinier", "Extraterrestre vert", "Alien à trois yeux", "Femme à barbe", "Homme le plus fort du monde", "Hercule de foire", "Homme-canon",
    "Avaleur de sabres", "Diseuse de bonne aventure", "Voyante", "Hypnotiseur", "Charmeur de serpents", "Fakir", "Prestidigitateur", "Prince grenouille",
    "Roi Midas", "Gorgone", "Ulysse", "Achille", "Cheval de Troie", "Icare", "Prométhée", "Atlas",
    "Narcisse", "Boîte de Pandore", "Sisyphe", "Orphée", "Marianne", "Jeanne d'Arc", "Charlemagne", "Louis XIV",
    "Vercingétorix", "Mozart", "Picasso", "Van Gogh", "Léonard de Vinci", "Shakespeare", "Molière", "Victor Hugo",
    "Marie Curie", "Neil Armstrong", "Abraham Lincoln", "Gandhi", "Toutânkhamon", "Néfertiti", "Attila", "Gengis Khan",
    "Barbe Noire", "Calamity Jane", "Billy the Kid", "Buffalo Bill"
  ],
  "Musique & arts": [
    "Guitare", "Guitare électrique", "Trompette", "Piano", "Violon", "Violoncelle", "Contrebasse", "Harpe",
    "Flûte", "Flûte de pan", "Clarinette", "Saxophone", "Trombone", "Tuba", "Cor", "Accordéon",
    "Harmonica", "Cornemuse", "Batterie", "Tambour", "Tam-tam", "Djembé", "Maracas", "Castagnettes",
    "Triangle", "Xylophone", "Cymbales", "Gong", "Ukulélé", "Banjo", "Mandoline", "Orgue",
    "Synthétiseur", "Platine vinyle", "Disque vinyle", "Cassette", "CD", "Micro", "Casque audio", "Enceinte",
    "Partition", "Note de musique", "Clé de sol", "Pupitre", "Orchestre", "Fanfare", "Chorale", "Concert",
    "Comédie musicale", "Rock", "Disco", "Boule à facettes", "Juke-box", "Boîte à musique", "Chevalet", "Palette de peinture",
    "Tube de peinture", "Aquarelle", "Fresque", "Graffiti", "Mosaïque", "Vitrail", "Sculpture", "Statue",
    "Buste", "Autoportrait", "Portrait", "Nature morte", "Caricature", "Bande dessinée", "Manga", "Dessin animé",
    "Film", "Clap de cinéma", "Caméra", "Projecteur", "Tapis rouge", "Rideau de théâtre", "Scène", "Masque de théâtre",
    "Joconde", "Vénus de Milo", "Penseur de Rodin", "Galerie d'art", "Exposition", "Selfie", "Album photo", "Pellicule",
    "Métronome", "Diapason", "Baguette de chef d'orchestre", "Flûte à bec", "Hautbois", "Basson", "Piccolo", "Cithare",
    "Sitar", "Balalaïka", "Steel drum", "Carillon", "Vielle à roue", "Orgue de Barbarie", "Guitare acoustique", "Basse électrique",
    "Ampli", "Table de mixage", "Platines de DJ", "Clip vidéo", "Festival de musique", "Fosse d'orchestre", "Loge d'artiste", "Autographe",
    "Disque d'or", "Hit-parade", "Feu de camp en chanson", "Pochette d'album", "Sculpture sur glace", "Sculpture en sable", "Statue de cire", "Bas-relief",
    "Gravure", "Estampe", "Pastel", "Fusain", "Croquis", "Esquisse", "Toile blanche", "Cadre doré",
    "Musée du Louvre", "Pyramide du Louvre", "Ombres chinoises", "Théâtre de marionnettes", "Guignol", "Cinéma muet", "Film d'horreur", "Western",
    "Film de science-fiction", "Opéra-rock", "Danse folklorique", "Flamenco", "Ténor", "Soprano", "Cor des Alpes", "Didgeridoo",
    "Kazoo", "Tambourin", "Bongos", "Timbales", "Grosse caisse", "Caisse claire", "Clavecin", "Luth",
    "Lyre", "Boîte à rythmes", "Gramophone", "Phonographe", "Magnétophone", "Radio-cassette", "Pochoir", "Collage",
    "Totem", "Marionnette géante"
  ],
  "Technologie & sciences": [
    "Téléphone", "Smartphone", "Ordinateur", "Ordinateur portable", "Tablette", "Clavier", "Souris d'ordinateur", "Écran",
    "Imprimante", "Scanner", "Clé USB", "Disque dur", "Câble", "Chargeur", "Batterie externe", "Wi-Fi",
    "Télévision", "Télécommande", "Console de jeux", "Manette", "Casque de réalité virtuelle", "Montre connectée", "Enceinte connectée", "Drone",
    "Imprimante 3D", "Calculatrice", "Radio", "Talkie-walkie", "Fax", "Minitel", "Webcam", "Code-barres",
    "QR code", "Emoji", "Smiley", "Hashtag", "Arobase", "Mot de passe", "Virus informatique", "Bug",
    "Pixel", "Internet", "Email", "Réseau social", "Notification", "Éolienne", "Électricité", "Atome",
    "Molécule", "Éprouvette", "Fiole", "Lunettes de protection", "Explosion", "Saturne", "Jupiter", "Mars",
    "Vénus", "Système solaire", "Astéroïde", "Rover martien", "Laser", "Radar", "Baromètre", "Sismographe",
    "Engrenage", "Ressort", "Levier", "Poulie", "Moteur", "Turbine", "Circuit électrique", "Puce électronique",
    "Processeur", "Carte mère", "Tableau périodique", "Équation", "Pi", "Infini", "Boulier", "Graphique",
    "Pourcentage", "Cube", "Sphère", "Cylindre", "Cône", "Carré", "Cercle", "Rectangle",
    "Losange", "Hexagone", "Spirale", "Point d'interrogation", "Point d'exclamation", "Hologramme", "Intelligence artificielle", "Robot aspirateur",
    "Fibre optique", "Data center", "Joystick", "Borne d'arcade", "Baladeur", "Lecteur MP3", "Magnétoscope", "Cassette vidéo",
    "DVD", "Distributeur de billets", "Parcmètre", "Caisse enregistreuse", "Porte automatique", "Paratonnerre", "Groupe électrogène", "Liseuse",
    "Écouteurs", "Écouteurs sans fil", "Perche à selfie", "Appareil photo instantané", "Projecteur vidéo", "Écran tactile", "Stylet", "Tapis de souris",
    "Ventilateur d'ordinateur", "Batterie de téléphone", "Coque de téléphone", "Câble HDMI", "Prise multiple", "Rallonge", "Interrupteur général", "Disjoncteur",
    "Compteur électrique", "Ampoule LED", "Néon", "Pile bouton", "Batterie de voiture", "Bobine électrique", "Générateur", "Dynamo",
    "Panneau photovoltaïque", "Réacteur nucléaire", "Accélérateur de particules", "Fusée Ariane", "Satellite météo", "Antenne parabolique", "Radiotélescope", "Sonde spatiale",
    "Télescope spatial", "Combinaison d'astronaute", "Gravité", "Pomme de Newton", "Ampoule d'Edison", "Machine à vapeur", "Imprimerie", "Levier de vitesse",
    "Thermomètre à mercure", "Pluviomètre", "Girouette", "Anémomètre", "Cadran solaire", "Clepsydre", "Sablier électronique", "Montre digitale",
    "Code secret", "Cadenas numérique", "Empreinte vocale", "Reconnaissance faciale", "Robot humanoïde", "Bras robotique", "Voiture autonome", "Exosquelette",
    "Microscope électronique", "Boîte de Petri", "Pipette", "Bec Bunsen", "Aimant en fer à cheval", "Prisme", "Arc électrique", "Batterie au citron",
    "Volcan en bicarbonate", "Bracelet connecté", "Lunettes connectées", "Frigo connecté", "Caméra de surveillance", "Détecteur de mouvement", "Détecteur de métaux", "Compteur Geiger",
    "Oscilloscope", "Multimètre", "Fer à souder", "Carte SIM", "Antenne relais", "Serveur informatique", "Console portable", "Visioconférence",
    "Appel vidéo", "Podcast", "Lampe solaire", "Voiture volante", "Vaisseau spatial", "Ascenseur spatial", "Nébuleuse", "Supernova",
    "Big Bang"
  ],
  "Actions": [
    "Dormir", "Manger", "Boire", "Courir", "Marcher", "Sauter", "Nager", "Danser",
    "Chanter", "Rire", "Pleurer", "Crier", "Chuchoter", "Lire", "Écrire", "Dessiner",
    "Cuisiner", "Conduire", "Voler", "Tomber", "Glisser", "Grimper", "Ramper", "Plonger",
    "Pêcher", "Chasser", "Jongler", "Applaudir", "Saluer", "Embrasser", "Faire un câlin", "Se brosser les dents",
    "Se laver les mains", "Prendre une douche", "Prendre un bain", "Se maquiller", "Se raser", "S'habiller", "Bâiller", "Éternuer",
    "Tousser", "Ronfler", "Rêver", "Réfléchir", "Compter", "Chercher", "Cacher un objet", "Montrer du doigt",
    "Pousser", "Tirer", "Porter", "Lancer", "Attraper", "Frapper", "Taper au clavier", "Donner un coup de pied",
    "Shooter", "Dribbler", "Pédaler", "Skier", "Patiner", "Surfer", "Ramer", "Escalader",
    "Faire du yoga", "Méditer", "Prier", "Se marier", "Fêter un anniversaire", "Souffler les bougies", "Ouvrir un cadeau", "Emballer un cadeau",
    "Faire les courses", "Payer", "Téléphoner", "Envoyer un message", "Prendre un selfie", "Prendre une photo", "Filmer", "Regarder la télé",
    "Écouter de la musique", "Jouer aux cartes", "Faire la vaisselle", "Passer l'aspirateur", "Repasser", "Étendre le linge", "Faire le lit", "Balayer",
    "Arroser les plantes", "Tondre la pelouse", "Planter un arbre", "Couper du bois", "Construire une maison", "Réparer", "Peindre un mur", "Coudre",
    "Promener le chien", "Caresser un chat", "Traire une vache", "Monter à cheval", "Faire du vélo", "Bronzer", "Se baigner", "Faire la planche",
    "Faire la sieste", "Se réveiller", "S'étirer", "Faire des pompes", "Faire le poirier", "Tirer la langue", "Hausser les épaules", "Se gratter la tête",
    "Se ronger les ongles", "Mâcher", "Avaler", "Goûter", "Sentir une fleur", "Renifler", "Siffler", "Hurler",
    "Rugir", "Aboyer", "Miauler", "Atterrir", "Décoller", "Couler", "Flotter", "Exploser",
    "Brûler", "Fondre", "Geler", "Grandir", "Vieillir", "Se battre", "Se disputer", "Se réconcilier",
    "Bouder", "Rougir", "Avoir peur", "Sursauter", "Trembler", "Frissonner", "Transpirer", "Avoir froid",
    "Avoir chaud", "Avoir faim", "Avoir soif", "S'ennuyer", "Être en retard", "Attendre le bus", "Faire la queue", "Faire du stop",
    "Se perdre", "Demander son chemin", "Voyager", "Faire sa valise", "Déménager", "Visiter un musée", "Acheter", "Vendre",
    "Arrêter un voleur", "Éteindre un feu", "Sauver quelqu'un", "Soigner", "Faire une piqûre", "Opérer", "Enseigner", "Apprendre",
    "Réviser", "Passer un examen", "Lever la main", "Tricher", "Mentir", "Gagner", "Perdre", "Encourager",
    "Faire la ola", "Trinquer", "Faire des crêpes", "Faire un gâteau", "Couper un oignon", "Éplucher une banane", "Casser un œuf", "Mélanger",
    "Servir", "Mettre la table", "Ranger sa chambre", "Faire un vœu", "Lancer une pièce", "Lancer les dés", "Se déguiser", "Se cacher",
    "Espionner", "Chatouiller", "Pincer", "Mordre", "Griffer", "Lécher", "Souffler", "Gonfler un ballon",
    "Éclater un ballon", "Faire des bulles", "Jouer du piano", "Jouer de la guitare", "Diriger un orchestre", "Faire un discours", "Voter", "Manifester",
    "Faire la fête", "Faire un feu de camp", "Raconter une histoire", "Se coucher", "Bercer un bébé", "Changer une couche", "Donner le biberon", "Marcher sur la lune",
    "Tomber amoureux", "Demander en mariage", "Se moucher", "Se brûler", "Se couper", "Glisser sur une peau de banane", "Faire un bonhomme de neige", "Faire un château de sable",
    "Faire la roue", "Jouer à cache-cache", "Faire une grimace", "Faire un clin d'œil", "Rouler", "Tourner en rond", "S'asseoir", "Se lever",
    "S'agenouiller", "Se pencher", "Ramasser", "Jeter", "Déchirer", "Plier", "Couper", "Coller",
    "Peser", "Mesurer", "Ouvrir une porte", "Fermer à clé", "Frapper à la porte", "Sonner", "Attendre", "Se dépêcher",
    "Fuir", "Poursuivre", "Se faufiler", "Marcher sur la pointe des pieds", "Tituber", "Trébucher", "Se cogner", "Faire un nœud",
    "Lacer ses chaussures", "Boutonner sa chemise", "Mettre son manteau", "Ouvrir un parapluie", "Faire du feu", "Allumer une bougie", "Éteindre la lumière", "Charger son téléphone",
    "Faire un selfie de groupe", "Jouer aux jeux vidéo", "Faire une sieste au soleil", "Regarder les étoiles", "Compter les moutons", "Faire un puzzle", "Jouer aux billes", "Sauter à la corde",
    "Faire de la balançoire", "Descendre le toboggan", "Faire du roller", "Faire du skate", "Jouer au foot", "Jouer au tennis", "Jouer à la marelle", "Faire une bataille d'eau",
    "Grimper à un arbre", "Sauter dans une flaque", "Patauger", "Éclabousser", "Faire des ricochets", "Construire une cabane", "Faire un avion en papier", "Faire voler un cerf-volant",
    "Souffler sur un pissenlit", "Cueillir des fleurs", "Ramasser des coquillages", "Griller des chamallows", "Faire de la luge", "Faire un ange dans la neige", "Jouer de la batterie", "Chanter sous la douche",
    "Danser le slow", "Sortir la poubelle", "Faire le ménage", "Plier le linge", "Nourrir les canards", "Brosser un cheval", "Laver la voiture", "Changer une roue",
    "Faire le plein", "Prendre l'avion", "Prendre le train", "Rater le bus", "Courir après le bus", "Faire du jogging"
  ],
  "Fêtes & traditions": [
    "Noël", "Sapin de Noël", "Guirlande", "Boule de Noël", "Calendrier de l'Avent", "Chaussette de Noël", "Bûche de Noël", "Couronne de l'Avent",
    "Nouvel An", "Feux d'artifice", "Pétard", "Confettis", "Serpentin", "Cotillons", "Coupe de champagne", "Compte à rebours",
    "Halloween", "Citrouille d'Halloween", "Un bonbon ou un sort", "Pâques", "Œuf de Pâques", "Chasse aux œufs", "Cloches de Pâques", "Carnaval",
    "Masque de carnaval", "Char de carnaval", "Défilé", "Saint-Valentin", "Bouquet de fleurs", "Boîte de chocolats", "Carte de vœux", "Anniversaire",
    "Gâteau d'anniversaire", "Bougies d'anniversaire", "Chapeau pointu", "Piñata", "Mariage", "Alliance", "Bouquet de la mariée", "Pièce montée",
    "Lune de miel", "Baptême", "Fête des mères", "Fête des pères", "Fête de la musique", "14 Juillet", "Bal populaire", "Feu de camp",
    "Galette des rois", "Fève", "Chandeleur", "Poisson d'avril", "Mardi gras", "Nouvel an chinois", "Lanterne chinoise", "Oktoberfest",
    "Thanksgiving", "Kermesse", "Tombola", "Loto", "Auto-tamponneuse", "Carrousel", "Manège", "Grande roue",
    "Montagnes russes", "Train fantôme", "Stand de tir", "Pêche aux canards", "Lâcher de ballons", "Remise des diplômes", "Diplôme", "Soirée pyjama",
    "Boum", "Faire-part", "Invitation", "Crèche de Noël", "Santon", "Marché de Noël", "Vin chaud", "Vacances",
    "Rentrée des classes", "Croisière", "Saint-Patrick", "Fête des voisins", "Vide-grenier", "Brocante", "Cérémonie", "Feu de la Saint-Jean",
    "Bal masqué", "Défilé militaire", "Fête nationale", "Fête du village", "Fête de fin d'année", "Spectacle de fin d'année", "Repas de famille", "Réveillon",
    "Dinde de Noël", "Lettre au Père Noël", "Cheminée de Noël", "Hotte du Père Noël", "Étoile du sapin", "Papier cadeau", "Nœud de cadeau", "Sapin enneigé",
    "Bonnet de Noël", "Pull moche de Noël", "Cadeau sous le sapin", "Galette à la frangipane", "Couronne en carton", "Crêpe qui saute", "Muguet du 1er mai", "Brin de muguet",
    "Cœur de Saint-Valentin", "Flèche de Cupidon", "Rose rouge", "Déclaration d'amour", "Fête d'Halloween", "Lanterne citrouille", "Toile d'araignée d'Halloween", "Bonbons d'Halloween",
    "Maison décorée", "Guirlande lumineuse", "Ballon en forme de cœur", "Gâteau à étages", "Bougie magique", "Cracker de Noël", "Mariage sur la plage", "Enterrement de vie de garçon",
    "Lancer de bouquet", "Première danse", "Photo de groupe", "Arbre de mai", "Feu de joie", "Lampion", "Couronne de Noël", "Biscuits de Noël",
    "Maison en pain d'épices", "Canne en sucre", "Père Fouettard", "Saint Nicolas", "Rois mages", "Étoile de Bethléem", "Lapin en chocolat", "Panier de Pâques",
    "Poule en chocolat", "Masque vénitien", "Lâcher de lanternes", "Danse du lion", "Soirée déguisée", "Haie d'honneur", "Vin d'honneur", "Pot de départ"
  ]
};
