// Mots secrets par catégorie : uniquement des mots simples et courants.
module.exports = {
  "Animaux": [
    "Girafe", "Éléphant", "Pieuvre", "Escargot", "Kangourou", "Pingouin", "Serpent", "Papillon",
    "Tortue", "Requin", "Hérisson", "Flamant rose", "Crocodile", "Chauve-souris", "Lapin", "Hibou",
    "Baleine", "Araignée", "Cheval", "Chameau", "Paon", "Crabe", "Singe", "Lion",
    "Tigre", "Zèbre", "Ours", "Ours polaire", "Panda", "Koala", "Loup", "Renard",
    "Écureuil", "Castor", "Blaireau", "Taupe", "Souris", "Rat", "Hamster", "Chat",
    "Chien", "Vache", "Taureau", "Mouton", "Chèvre", "Cochon", "Poule", "Coq",
    "Poussin", "Canard", "Oie", "Dinde", "Âne", "Lama", "Alpaga", "Dromadaire",
    "Hippopotame", "Rhinocéros", "Gorille", "Chimpanzé", "Lémurien", "Paresseux", "Tatou", "Fourmilier",
    "Ornithorynque", "Suricate", "Hyène", "Guépard", "Léopard", "Panthère", "Jaguar", "Lynx",
    "Puma", "Bison", "Buffle", "Élan", "Cerf", "Biche", "Chevreuil", "Sanglier",
    "Antilope", "Gazelle", "Gnou", "Morse", "Phoque", "Otarie", "Loutre", "Dauphin",
    "Orque", "Narval", "Cachalot", "Méduse", "Étoile de mer", "Hippocampe", "Homard", "Crevette",
    "Calamar", "Huître", "Moule", "Oursin", "Corail", "Poisson rouge", "Poisson-clown", "Raie",
    "Espadon", "Saumon", "Thon", "Truite", "Sardine", "Anguille", "Piranha", "Carpe",
    "Grenouille", "Crapaud", "Salamandre", "Lézard", "Caméléon", "Iguane", "Gecko", "Cobra",
    "Python", "Vipère", "Boa", "Alligator", "Aigle", "Faucon", "Vautour", "Condor",
    "Chouette", "Corbeau", "Pie", "Pigeon", "Colombe", "Moineau", "Merle", "Mésange",
    "Hirondelle", "Perroquet", "Perruche", "Toucan", "Colibri", "Pélican", "Mouette", "Albatros",
    "Cigogne", "Héron", "Cygne", "Autruche", "Kiwi", "Dodo", "Manchot", "Fourmi",
    "Abeille", "Guêpe", "Frelon", "Bourdon", "Coccinelle", "Libellule", "Sauterelle", "Criquet",
    "Grillon", "Cigale", "Mouche", "Moustique", "Puce", "Pou", "Cafard", "Scarabée",
    "Chenille", "Ver de terre", "Limace", "Mille-pattes", "Scorpion", "Luciole", "Termite", "Chiot",
    "Chaton", "Poulain", "Veau", "Agneau", "Têtard", "Lionceau", "Ourson", "Dinosaure",
    "Tyrannosaure", "Tricératops", "Diplodocus", "Ptérodactyle", "Mammouth", "Chinchilla", "Furet", "Hermine",
    "Belette", "Mangouste", "Porc-épic", "Marmotte", "Renne", "Caribou", "Babouin", "Ouistiti",
    "Coyote", "Fennec", "Bélier", "Bouc", "Jument", "Poney", "Mulet", "Requin-marteau",
    "Faisan", "Rossignol", "Canari", "Lièvre", "Caniche", "Dalmatien", "Chihuahua", "Bouledogue",
    "Oiseau", "Ver", "Insecte", "Poisson"
  ],
  "Nourriture": [
    "Pizza", "Banane", "Croissant", "Hamburger", "Glace", "Spaghetti", "Ananas", "Baguette",
    "Fromage", "Sushi", "Pastèque", "Cerise", "Œuf au plat", "Carotte", "Gâteau", "Hot-dog",
    "Brocoli", "Popcorn", "Donut", "Raisin", "Fraise", "Taco", "Crêpe", "Pomme",
    "Poire", "Orange", "Citron", "Pamplemousse", "Mandarine", "Mangue", "Noix de coco", "Grenade",
    "Figue", "Abricot", "Pêche", "Prune", "Framboise", "Myrtille", "Mûre", "Melon",
    "Litchi", "Tomate", "Concombre", "Courgette", "Aubergine", "Poivron", "Piment", "Oignon",
    "Ail", "Poireau", "Chou", "Chou-fleur", "Épinard", "Salade", "Laitue", "Radis",
    "Navet", "Betterave", "Céleri", "Asperge", "Artichaut", "Haricot vert", "Petit pois", "Maïs",
    "Pomme de terre", "Potiron", "Citrouille", "Courge", "Gingembre", "Persil", "Basilic", "Menthe",
    "Lentilles", "Riz", "Pâtes", "Lasagnes", "Ravioli", "Couscous", "Paella", "Risotto",
    "Quiche", "Macaron", "Madeleine", "Cookie", "Muffin", "Cupcake", "Brownie", "Gaufre",
    "Pancake", "Churros", "Beignet", "Pain au chocolat", "Brioche", "Tartine", "Sandwich", "Croque-monsieur",
    "Kebab", "Burrito", "Nachos", "Frites", "Chips", "Nuggets", "Saucisse", "Jambon",
    "Saucisson", "Bacon", "Steak", "Ratatouille", "Cassoulet", "Choucroute", "Raclette", "Fondue",
    "Gratin", "Purée", "Soupe", "Omelette", "Camembert", "Mozzarella", "Yaourt", "Beurre",
    "Lait", "Miel", "Confiture", "Chocolat", "Bonbon", "Sucette", "Barbe à papa", "Guimauve",
    "Caramel", "Réglisse", "Chewing-gum", "Pomme d'amour", "Flan", "Tiramisu", "Crumble", "Sorbet",
    "Esquimau", "Milkshake", "Smoothie", "Jus d'orange", "Café", "Thé", "Chocolat chaud", "Limonade",
    "Soda", "Vin", "Bière", "Champagne", "Cocktail", "Cacahuète", "Noisette", "Noix",
    "Amande", "Pistache", "Châtaigne", "Olive", "Cornichon", "Ketchup", "Moutarde", "Mayonnaise",
    "Sel", "Poivre", "Sucre", "Farine", "Huile", "Caviar", "Bretzel", "Nems",
    "Ramen", "Curry", "Tortilla", "Brochette", "Panini", "Nougat", "Truffe", "Vanille",
    "Céréales", "Pain d'épices", "Meringue", "Grenadine", "Sirop", "Cheesecake", "Biscuit", "Galette",
    "Crème", "Poulet", "Œuf", "Salami", "Viande", "Glaçon", "Pain", "Haricot",
    "Eau", "Jus", "Fruit", "Tarte"
  ],
  "Objets": [
    "Parapluie", "Lunettes", "Ciseaux", "Ampoule", "Clé", "Bougie", "Horloge", "Ballon",
    "Valise", "Appareil photo", "Marteau", "Brosse à dents", "Échelle", "Cadenas", "Télescope", "Couronne",
    "Sablier", "Boussole", "Crayon", "Stylo", "Gomme", "Règle", "Taille-crayon", "Cahier",
    "Livre", "Cartable", "Trousse", "Agrafeuse", "Punaise", "Colle", "Pinceau", "Enveloppe",
    "Timbre", "Calendrier", "Loupe", "Microscope", "Jumelles", "Lampe de poche", "Briquet", "Allumette",
    "Pile", "Aimant", "Montre", "Réveil", "Portefeuille", "Porte-monnaie", "Tirelire", "Sac à dos",
    "Sac à main", "Panier", "Seau", "Pelle", "Râteau", "Arrosoir", "Brouette", "Tournevis",
    "Pince", "Scie", "Perceuse", "Clou", "Hache", "Corde", "Chaîne", "Cintre",
    "Aiguille", "Bouton", "Peigne", "Sèche-cheveux", "Rasoir", "Miroir", "Parfum", "Rouge à lèvres",
    "Savon", "Dentifrice", "Éponge", "Serviette", "Mouchoir", "Pansement", "Thermomètre", "Seringue",
    "Béquille", "Fauteuil roulant", "Biberon", "Tétine", "Hochet", "Doudou", "Poupée", "Peluche",
    "Toupie", "Yoyo", "Cerf-volant", "Billes", "Dé", "Puzzle", "Domino", "Balançoire",
    "Toboggan", "Château de sable", "Bulle de savon", "Masque", "Éventail", "Canne", "Drapeau", "Trophée",
    "Médaille", "Coupe", "Ruban", "Cadeau", "Boîte", "Carton", "Caisse", "Coffre au trésor",
    "Bouteille", "Verre", "Tasse", "Bol", "Assiette", "Fourchette", "Couteau", "Cuillère",
    "Baguettes", "Paille", "Casserole", "Poêle", "Marmite", "Louche", "Fouet", "Passoire",
    "Tire-bouchon", "Théière", "Cafetière", "Bouilloire", "Grille-pain", "Mixeur", "Gourde", "Saladier",
    "Plateau", "Chandelier", "Lanterne", "Plume", "Badge", "Sifflet", "Mégaphone", "Cloche",
    "Sonnette", "Boîte aux lettres", "Poubelle", "Balai", "Ventilateur", "Radiateur", "Extincteur", "Canne à pêche",
    "Tente", "Hamac", "Parasol", "Bouée", "Palmes", "Lunettes de soleil", "Glacière", "Boule de cristal",
    "Baguette magique", "Fer à cheval", "Cible", "Arc", "Flèche", "Bouclier", "Épée", "Armure",
    "Casque", "Catapulte", "Canon", "Dynamite", "Menottes", "Cage", "Niche", "Laisse",
    "Aquarium", "Pipe", "Origami", "Ticket", "Passeport", "Tableau noir", "Craie", "Feutre",
    "Compas", "Ardoise", "Scotch", "Brosse", "Mug", "Fourche", "Bombe", "Pioche",
    "Boule", "Bidon", "Lasso", "Carnet", "Pot", "Magazine", "Affiche", "Carte",
    "Tonneau", "Bulle", "Lettre", "Canette", "Bâton", "Couvercle", "Coffre", "Bouchon",
    "Filet", "Journal", "Cadre", "Sac", "Fil", "Balle", "Tuyau", "Jouet"
  ],
  "Maison": [
    "Chaise", "Table", "Lit", "Canapé", "Fauteuil", "Armoire", "Commode", "Étagère",
    "Bureau", "Tabouret", "Banc", "Lit superposé", "Berceau", "Matelas", "Oreiller", "Couette",
    "Drap", "Coussin", "Tapis", "Rideau", "Lampe", "Lustre", "Abat-jour", "Lampadaire",
    "Interrupteur", "Fenêtre", "Porte", "Volet", "Paillasson", "Escalier", "Ascenseur", "Cheminée",
    "Toit", "Grenier", "Cave", "Garage", "Balcon", "Terrasse", "Jardin", "Clôture",
    "Portail", "Pelouse", "Tondeuse", "Barbecue", "Nain de jardin", "Cabane", "Salle de bain", "Baignoire",
    "Douche", "Lavabo", "Robinet", "Toilettes", "Papier toilette", "Peignoir", "Cuisine", "Frigo",
    "Congélateur", "Four", "Micro-ondes", "Cuisinière", "Évier", "Lave-vaisselle", "Lave-linge", "Fer à repasser",
    "Aspirateur", "Tableau", "Vase", "Pot de fleurs", "Porte-manteau", "Placard", "Tiroir", "Coffre-fort",
    "Alarme", "Escabeau", "Papier peint", "Plafond", "Mur", "Brique", "Antenne", "Bûche",
    "Pouf", "Veilleuse", "Salière", "Carafe", "Torchon", "Tablier", "Balance", "Friteuse",
    "Chambre", "Salon", "Table basse", "Couverture", "Poignée", "Bain", "Plante"
  ],
  "Lieux": [
    "Plage", "Hôpital", "Aéroport", "Bibliothèque", "Cinéma", "Piscine", "Boulangerie", "Château",
    "Église", "Gare", "Phare", "Zoo", "Musée", "Prison", "Stade", "Cirque",
    "Supermarché", "École", "Tour Eiffel", "Île déserte", "Camping", "Ferme", "Pyramide", "Collège",
    "Lycée", "Université", "Mairie", "Banque", "Pharmacie", "Boucherie", "Marché", "Centre commercial",
    "Fleuriste", "Librairie", "Restaurant", "Bar", "Pizzeria", "Fast-food", "Crêperie", "Hôtel",
    "Théâtre", "Opéra", "Patinoire", "Gymnase", "Parc", "Aire de jeux", "Parc d'attractions", "Fête foraine",
    "Laboratoire", "Usine", "Chantier", "Port", "Pont", "Tunnel", "Autoroute", "Rond-point",
    "Parking", "Station-service", "Gratte-ciel", "Immeuble", "Maison", "Igloo", "Tipi", "Chalet",
    "Moulin", "Moulin à vent", "Grange", "Écurie", "Poulailler", "Serre", "Verger", "Champ",
    "Cimetière", "Cathédrale", "Mosquée", "Temple", "Fort", "Donjon", "Ruines", "Arc de triomphe",
    "Colisée", "Statue de la Liberté", "Big Ben", "Tour de Pise", "Muraille de Chine", "Sphinx", "Venise", "Paris",
    "Londres", "Rome", "Tokyo", "Égypte", "Japon", "Chine", "Inde", "Mexique",
    "Brésil", "Canada", "Australie", "Afrique", "Pôle Nord", "Antarctique", "Station spatiale", "Salle de classe",
    "Cantine", "Tribunal", "Palais", "Manoir", "Maison hantée", "Labyrinthe", "Mine", "Barrage",
    "Puits", "Fontaine", "Kiosque", "Cabine téléphonique", "Spa", "Ranch", "Saloon", "Arène",
    "Casino", "Village", "Ville", "Rue", "Château fort", "Sahara", "Hollywood", "Terrain",
    "Boutique", "Station", "Magasin", "Tour", "Piste"
  ],
  "Métiers": [
    "Pompier", "Astronaute", "Cuisinier", "Médecin", "Policier", "Magicien", "Clown", "Plongeur",
    "Peintre", "Jardinier", "Boxeur", "Pilote", "Facteur", "Dentiste", "Cow-boy", "Musicien",
    "Photographe", "Infirmier", "Chirurgien", "Vétérinaire", "Pharmacien", "Sage-femme", "Professeur", "Scientifique",
    "Archéologue", "Astronome", "Inventeur", "Ingénieur", "Architecte", "Informaticien", "Hacker", "Youtubeur",
    "Influenceur", "Journaliste", "Reporter", "Écrivain", "Poète", "Acteur", "Réalisateur", "Cascadeur",
    "Chanteur", "DJ", "Danseur", "Mannequin", "Styliste", "Couturier", "Coiffeur", "Tatoueur",
    "Boulanger", "Pâtissier", "Boucher", "Serveur", "Barman", "Caissier", "Vendeur", "Livreur",
    "Chauffeur de taxi", "Hôtesse de l'air", "Capitaine", "Marin", "Pêcheur", "Fermier", "Berger", "Apiculteur",
    "Bûcheron", "Maçon", "Charpentier", "Menuisier", "Plombier", "Électricien", "Serrurier", "Mécanicien",
    "Garagiste", "Forgeron", "Éboueur", "Balayeur", "Concierge", "Gardien", "Garde du corps", "Détective",
    "Espion", "Agent secret", "Gendarme", "Militaire", "Soldat", "Général", "Parachutiste", "Juge",
    "Avocat", "Maire", "Président", "Maître-nageur", "Sauveteur", "Entraîneur", "Arbitre", "Footballeur",
    "Jockey", "Torero", "Dresseur", "Dompteur", "Jongleur", "Acrobate", "Trapéziste", "Funambule",
    "Mime", "Marionnettiste", "Ventriloque", "Ramoneur", "Mineur", "Sculpteur", "Potier", "Dessinateur",
    "Chef d'orchestre", "Pianiste", "Violoniste", "Batteur", "Guitariste", "Rappeur", "Moine", "Prêtre",
    "Pape", "Explorateur", "Alpiniste", "Chasseur", "Baby-sitter", "Coureur", "Surfeur", "Skieur",
    "Docteur", "Cycliste", "Garde", "Chauffeur", "Nageur", "Ouvrier", "Artiste", "Chef",
    "Guide"
  ],
  "Sports & loisirs": [
    "Football", "Tennis", "Ski", "Surf", "Basket", "Bowling", "Golf", "Natation",
    "Escalade", "Karaté", "Échecs", "Skateboard", "Plongée", "Équitation", "Danse", "Cyclisme",
    "Tir à l'arc", "Ping-pong", "Yoga", "Rugby", "Handball", "Volley-ball", "Baseball", "Hockey sur glace",
    "Badminton", "Boxe", "Judo", "Kung-fu", "Sumo", "Escrime", "Musculation", "Gymnastique",
    "Trampoline", "Saut à la perche", "Marathon", "Course à pied", "Sprint", "Relais", "Triathlon", "Patin à glace",
    "Roller", "Luge", "Bobsleigh", "Snowboard", "Curling", "Randonnée", "Parapente", "Parachutisme",
    "Deltaplane", "Saut à l'élastique", "Kitesurf", "Planche à voile", "Ski nautique", "Aviron", "Canoë", "Kayak",
    "Rafting", "Water-polo", "Plongeon", "Voile", "Motocross", "Formule 1", "Rallye", "Karting",
    "BMX", "VTT", "Pétanque", "Billard", "Fléchettes", "Mini-golf", "Babyfoot", "Flipper",
    "Jeu vidéo", "Dames", "Poker", "Mots croisés", "Sudoku", "Tricot", "Couture", "Peinture",
    "Dessin", "Jardinage", "Bricolage", "Karaoké", "Jonglage", "Frisbee", "Corde à sauter", "Marelle",
    "Cache-cache", "Pierre-feuille-ciseaux", "Pique-nique", "Chasse au trésor", "Paintball", "Polo", "Boomerang", "Haltères",
    "Ballon de foot", "Raquette", "Gant de boxe", "Podium", "Coupe du monde", "Jeux olympiques", "Carton rouge", "Penalty",
    "But", "Panier de basket", "Hoverboard", "Échasses", "Hula hoop", "Diabolo", "Hip-hop", "Breakdance",
    "Salsa", "Tango", "Valse", "Claquettes", "Ballet", "Moonwalk", "Rodéo", "Pompes",
    "Abdos", "Grand écart", "Poirier", "Roue", "Mikado", "Bataille navale", "Morpion", "Pendu",
    "Memory", "Équipe", "Course", "Saut", "Match", "Quiz", "Patin", "Champion",
    "Bingo"
  ],
  "Nature": [
    "Arc-en-ciel", "Cactus", "Tornade", "Soleil", "Lune", "Éclair", "Cascade", "Palmier",
    "Flocon de neige", "Tournesol", "Nuage", "Étoile filante", "Rose", "Champignon", "Vague", "Sapin",
    "Feuille", "Coquillage", "Grotte", "Rivière", "Montagne", "Désert", "Volcan", "Jungle",
    "Savane", "Prairie", "Oasis", "Forêt", "Lac", "Étang", "Mare", "Océan",
    "Mer", "Île", "Falaise", "Colline", "Vallée", "Canyon", "Iceberg", "Banquise",
    "Geyser", "Ruisseau", "Fleuve", "Dune", "Marée", "Tsunami", "Ouragan", "Tempête",
    "Orage", "Pluie", "Grêle", "Neige", "Brouillard", "Givre", "Avalanche", "Tremblement de terre",
    "Lave", "Inondation", "Vent", "Aurore boréale", "Coucher de soleil", "Éclipse", "Étoile", "Constellation",
    "Planète", "Comète", "Météorite", "Galaxie", "Voie lactée", "Trou noir", "Arbre", "Chêne",
    "Saule pleureur", "Baobab", "Bambou", "Bonsaï", "Cocotier", "Pin", "Olivier", "Pommier",
    "Racine", "Tronc", "Branche", "Pomme de pin", "Gland", "Marron", "Fleur", "Tulipe",
    "Marguerite", "Coquelicot", "Orchidée", "Lavande", "Muguet", "Pissenlit", "Lotus", "Nénuphar",
    "Trèfle", "Trèfle à quatre feuilles", "Herbe", "Fougère", "Algue", "Houx", "Plante carnivore", "Graine",
    "Botte de foin", "Rocher", "Caillou", "Sable", "Boue", "Cristal", "Diamant", "Fossile",
    "Terre", "Feu", "Fumée", "Goutte d'eau", "Bonhomme de neige", "Boule de neige", "Toile d'araignée", "Nid d'oiseau",
    "Ruche", "Fourmilière", "Printemps", "Été", "Automne", "Hiver", "Pleine lune", "Ombre",
    "Sommet", "Chemin", "Perle", "Feuille morte", "Ciel", "Bois", "Jour", "Univers",
    "Pierre", "Nuit", "Espace"
  ],
  "Transports": [
    "Vélo", "Fusée", "Voiture", "Camion", "Bus", "Tramway", "Métro", "Train",
    "TGV", "Wagon", "Moto", "Scooter", "Trottinette", "Monocycle", "Tandem", "Tricycle",
    "Taxi", "Limousine", "Décapotable", "Jeep", "Quatre-quatre", "Quad", "Camping-car", "Caravane",
    "Remorque", "Dépanneuse", "Camion de pompiers", "Ambulance", "Voiture de police", "Bulldozer", "Pelleteuse", "Tracteur",
    "Kart", "Voiture de course", "Char d'assaut", "Avion", "Avion en papier", "Planeur", "Hélicoptère", "Montgolfière",
    "Dirigeable", "Jetpack", "Navette spatiale", "Soucoupe volante", "Satellite", "Parachute", "Bateau", "Voilier",
    "Paquebot", "Ferry", "Barque", "Pirogue", "Radeau", "Yacht", "Jet-ski", "Sous-marin",
    "Bateau pirate", "Drakkar", "Gondole", "Pédalo", "Paddle", "Porte-avions", "Téléphérique", "Télésiège",
    "Calèche", "Carrosse", "Traîneau", "Poussette", "Landau", "Bus scolaire", "Panneau stop", "Feu rouge",
    "Passage piéton", "Volant", "Pneu", "Klaxon", "Rétroviseur", "Essuie-glace", "Ceinture de sécurité", "Ancre",
    "Hélice", "Hublot", "Rame", "Rails", "Locomotive", "Navire", "Route", "Panneau",
    "Essence"
  ],
  "Vêtements & accessoires": [
    "Chapeau", "Casquette", "Bonnet", "Béret", "Chapeau de paille", "Haut-de-forme", "Sombrero", "Cagoule",
    "Écharpe", "Foulard", "Cravate", "Nœud papillon", "Gants", "Moufles", "Chaussettes", "Chaussures",
    "Baskets", "Bottes", "Bottes de pluie", "Sandales", "Tongs", "Chaussons", "Pantoufles", "Talons hauts",
    "T-shirt", "Chemise", "Pull", "Sweat à capuche", "Gilet", "Veste", "Blouson", "Manteau",
    "Doudoune", "Imperméable", "Cape", "Poncho", "Smoking", "Costume", "Robe", "Robe de mariée",
    "Jupe", "Tutu", "Short", "Pantalon", "Jean", "Salopette", "Combinaison", "Pyjama",
    "Robe de chambre", "Maillot de bain", "Bikini", "Slip", "Soutien-gorge", "Kilt", "Kimono", "Uniforme",
    "Scaphandre", "Gilet jaune", "Ceinture", "Bretelles", "Bracelet", "Collier", "Bague", "Boucles d'oreilles",
    "Diadème", "Serre-tête", "Perruque", "Moustache", "Barbe", "Monocle", "Cache-œil", "Bavoir",
    "Couche", "Lacet", "Poche", "Col roulé", "Capuche", "Paillettes", "Turban", "Bandana",
    "Déguisement", "Porte-clés", "Chapeau de sorcière", "Jogging", "Bijou"
  ],
  "Corps & santé": [
    "Main", "Pied", "Bras", "Jambe", "Tête", "Œil", "Nez", "Bouche",
    "Oreille", "Dent", "Langue", "Lèvres", "Cheveux", "Sourcil", "Front", "Joue",
    "Menton", "Cou", "Épaule", "Coude", "Poignet", "Doigt", "Pouce", "Ongle",
    "Genou", "Cheville", "Orteil", "Talon", "Dos", "Ventre", "Nombril", "Fesses",
    "Cœur", "Cerveau", "Squelette", "Crâne", "Os", "Muscle", "Biceps", "Sang",
    "Peau", "Grain de beauté", "Tache de rousseur", "Tatouage", "Piercing", "Cicatrice", "Rhume", "Fièvre",
    "Toux", "Hoquet", "Mal de dents", "Mal de tête", "Jambe cassée", "Plâtre", "Bandage", "Vaccin",
    "Pilule", "Médicament", "Stéthoscope", "Appareil dentaire", "Virus", "Sourire", "Clin d'œil", "Grimace",
    "Larme", "Cauchemar", "Rêve", "Poing", "Câlin", "Bisou", "Bébé", "Jumeaux",
    "Femme enceinte", "Chauve", "Queue de cheval", "Tresse", "Pouce levé", "Poignée de main", "Bras de fer", "Coup de soleil",
    "Œil au beurre noir", "Dent de lait", "Cuisse", "Nez rouge", "Pieds nus", "Corps", "Visage", "Blessure",
    "Malade"
  ],
  "Personnages & fantastique": [
    "Pirate", "Chevalier", "Sorcière", "Princesse", "Prince", "Roi", "Reine", "Fée",
    "Elfe", "Lutin", "Nain", "Géant", "Ogre", "Troll", "Dragon", "Licorne",
    "Sirène", "Cyclope", "Phénix", "Yéti", "Monstre du Loch Ness", "Vampire", "Loup-garou", "Zombie",
    "Momie", "Fantôme", "Frankenstein", "Diable", "Ange", "Sorcier", "Génie", "Lampe magique",
    "Tapis volant", "Chaudron", "Balai de sorcière", "Potion magique", "Super-héros", "Robot", "Extraterrestre", "Martien",
    "Ninja", "Samouraï", "Viking", "Gladiateur", "Shérif", "Bandit", "Voleur", "Robin des Bois",
    "Zorro", "Père Noël", "Petit Chaperon rouge", "Grand méchant loup", "Trois petits cochons", "Blanche-Neige", "Cendrillon", "Raiponce",
    "Pinocchio", "Peter Pan", "Capitaine Crochet", "Lapin blanc", "Petit Poucet", "Chat botté", "Aladdin", "Ali Baba",
    "Hercule", "Zeus", "Poséidon", "Cupidon", "Pharaon", "Cléopâtre", "Napoléon", "Jules César",
    "Christophe Colomb", "Einstein", "Dracula", "Sherlock Holmes", "Tarzan", "Le Petit Prince", "Épouvantail", "Marionnette",
    "Petite souris", "Marchand de sable", "Lapin de Pâques", "Archer", "Roi Arthur", "Trésor", "Jambe de bois", "Tête de mort",
    "Cercueil", "Pierre tombale", "Chat noir", "Trône", "Reine des neiges", "OVNI", "Sabre laser", "Machine à remonter le temps",
    "Prince charmant", "Belle et la Bête", "Petite sirène", "Boucle d'or", "Soldat de plomb", "Casse-noisette", "Homme invisible", "Cheval de Troie",
    "Jeanne d'Arc", "Mozart", "Picasso", "Van Gogh", "Léonard de Vinci", "Empereur", "Héros", "Alien",
    "Monstre"
  ],
  "Musique & arts": [
    "Guitare", "Guitare électrique", "Trompette", "Piano", "Violon", "Harpe", "Flûte", "Flûte de pan",
    "Clarinette", "Saxophone", "Trombone", "Tuba", "Accordéon", "Harmonica", "Cornemuse", "Batterie",
    "Tambour", "Tam-tam", "Maracas", "Triangle", "Xylophone", "Cymbales", "Gong", "Ukulélé",
    "Banjo", "Orgue", "Disque vinyle", "Cassette", "CD", "Micro", "Casque audio", "Enceinte",
    "Note de musique", "Clé de sol", "Orchestre", "Fanfare", "Concert", "Boule à facettes", "Juke-box", "Boîte à musique",
    "Palette de peinture", "Graffiti", "Sculpture", "Statue", "Portrait", "Bande dessinée", "Manga", "Dessin animé",
    "Film", "Caméra", "Projecteur", "Tapis rouge", "Scène", "Joconde", "Selfie", "Album photo",
    "Flûte à bec", "Grosse caisse", "Photo", "Spectacle", "Chanson", "Disque"
  ],
  "Technologie & sciences": [
    "Téléphone", "Smartphone", "Ordinateur", "Ordinateur portable", "Tablette", "Clavier", "Écran", "Imprimante",
    "Scanner", "Clé USB", "Câble", "Chargeur", "Wi-Fi", "Télévision", "Télécommande", "Console de jeux",
    "Manette", "Montre connectée", "Drone", "Imprimante 3D", "Calculatrice", "Radio", "Talkie-walkie", "Webcam",
    "Code-barres", "QR code", "Emoji", "Smiley", "Hashtag", "Mot de passe", "Bug", "Internet",
    "Email", "Réseau social", "Éolienne", "Atome", "Éprouvette", "Explosion", "Saturne", "Jupiter",
    "Mars", "Vénus", "Système solaire", "Astéroïde", "Laser", "Radar", "Engrenage", "Ressort",
    "Moteur", "Infini", "Cube", "Sphère", "Cylindre", "Cône", "Carré", "Cercle",
    "Rectangle", "Losange", "Hexagone", "Spirale", "Point d'interrogation", "Point d'exclamation", "Robot aspirateur", "Joystick",
    "DVD", "Distributeur de billets", "Caisse enregistreuse", "Écouteurs", "Code secret", "Détecteur de métaux", "Voiture volante", "Vaisseau spatial",
    "Machine", "Vidéo", "Message", "Prise", "Code"
  ],
  "Actions": [
    "Dormir", "Manger", "Boire", "Courir", "Marcher", "Sauter", "Nager", "Danser",
    "Chanter", "Rire", "Pleurer", "Crier", "Lire", "Écrire", "Dessiner", "Cuisiner",
    "Conduire", "Voler", "Tomber", "Glisser", "Grimper", "Ramper", "Plonger", "Pêcher",
    "Chasser", "Jongler", "Applaudir", "Saluer", "Embrasser", "Faire un câlin", "Se brosser les dents", "Prendre une douche",
    "S'habiller", "Bâiller", "Éternuer", "Tousser", "Ronfler", "Rêver", "Réfléchir", "Compter",
    "Chercher", "Pousser", "Tirer", "Porter", "Lancer", "Attraper", "Frapper", "Pédaler",
    "Skier", "Patiner", "Surfer", "Ramer", "Escalader", "Faire du yoga", "Se marier", "Souffler les bougies",
    "Ouvrir un cadeau", "Faire les courses", "Payer", "Téléphoner", "Prendre une photo", "Filmer", "Regarder la télé", "Jouer aux cartes",
    "Faire la vaisselle", "Balayer", "Réparer", "Coudre", "Promener le chien", "Monter à cheval", "Faire du vélo", "Bronzer",
    "Faire la sieste", "Se réveiller", "Faire des pompes", "Faire le poirier", "Tirer la langue", "Goûter", "Siffler", "Hurler",
    "Rugir", "Aboyer", "Miauler", "Couler", "Flotter", "Exploser", "Brûler", "Fondre",
    "Rougir", "Avoir peur", "Trembler", "Avoir froid", "Avoir faim", "Voyager", "Acheter", "Lever la main",
    "Mentir", "Gagner", "Perdre", "Trinquer", "Se cacher", "Chatouiller", "Mordre", "Lécher",
    "Souffler", "Faire des bulles", "Jouer du piano", "Jouer de la guitare", "Se coucher", "Tomber amoureux", "Se moucher", "Faire la roue",
    "Faire une grimace", "S'asseoir", "Ramasser", "Jeter", "Plier", "Couper", "Attendre", "Ouvrir",
    "Brosser", "Écouter", "Casser", "Fermer", "Laver", "Caresser", "Découper", "Cueillir",
    "Construire", "Appeler", "Regarder", "Éteindre", "Peindre", "Planter", "Neiger", "Jouer",
    "Colorier", "Montrer", "Nourrir", "Allumer", "Gonfler", "Arroser", "Promener", "Parler",
    "Peigner", "Cacher", "Pleuvoir"
  ],
  "Fêtes & traditions": [
    "Noël", "Sapin de Noël", "Guirlande", "Boule de Noël", "Calendrier de l'Avent", "Chaussette de Noël", "Bûche de Noël", "Nouvel An",
    "Feux d'artifice", "Pétard", "Confettis", "Halloween", "Pâques", "Œuf de Pâques", "Carnaval", "Défilé",
    "Saint-Valentin", "Bouquet de fleurs", "Anniversaire", "Gâteau d'anniversaire", "Chapeau pointu", "Piñata", "Mariage", "Alliance",
    "Pièce montée", "Lune de miel", "14 Juillet", "Feu de camp", "Galette des rois", "Poisson d'avril", "Mardi gras", "Lanterne chinoise",
    "Auto-tamponneuse", "Manège", "Grande roue", "Montagnes russes", "Train fantôme", "Pêche aux canards", "Diplôme", "Soirée pyjama",
    "Vacances", "Croisière", "Bal masqué", "Papier cadeau", "Canne en sucre", "Rois mages", "Mariée", "Fête",
    "Bouquet", "Parade", "Bal"
  ]
};
